/*
 * File: app/store/EmpPaymentsStore.js
 * Date: Fri Aug 25 2023 08:32:18 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.store.EmpPaymentsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.emppaymentsstore',

    requires: [
        'PayrollApp.model.EmpPayments',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'EmpPaymentsStore',
            model: 'PayrollApp.model.EmpPayments',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getEmpPayments',
                reader: {
                    type: 'json',
                    rootProperty: 'empPayments'
                }
            }
        }, cfg)]);
    }
});