/*
 * File: app/store/PayMonthsStore.js
 * Date: Thu Aug 24 2023 19:15:49 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.store.PayMonthsStore', {
    extend: 'Ext.data.Store',
    alias: 'store.paymonthsstore',

    requires: [
        'PayrollApp.model.PayrollMonths',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'PayMonthsStore',
            model: 'PayrollApp.model.PayrollMonths',
            data: [
                [
                    '1',
                    'January'
                ],
                [
                    '2',
                    'February'
                ],
                [
                    '3',
                    'March'
                ],
                [
                    '4',
                    'April'
                ],
                [
                    '5',
                    'May'
                ],
                [
                    '6',
                    'June'
                ],
                [
                    '7',
                    'July'
                ],
                [
                    '8',
                    'August'
                ],
                [
                    '9',
                    'September'
                ],
                [
                    '10',
                    'October'
                ],
                [
                    '11',
                    'November'
                ],
                [
                    '12',
                    'December'
                ]
            ],
            proxy: {
                type: 'ajax',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});