/*
 * File: app/store/PayMonthStore.js
 * Date: Sun Mar 08 2015 15:46:55 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.store.PayMonthStore', {
    extend: 'Ext.data.Store',
    alias: 'store.paymonthstore',

    requires: [
        'PayrollApp.model.PayrollMonths'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'PayrollApp.model.PayrollMonths',
            storeId: 'MyStore',
            data: [
                [
                    'January',
                    'January'
                ],
                [
                    'February',
                    'February'
                ],
                [
                    'March',
                    'March'
                ],
                [
                    'April',
                    'April'
                ],
                [
                    'May',
                    'May'
                ],
                [
                    'June',
                    'June'
                ],
                [
                    'July',
                    'July'
                ],
                [
                    'August',
                    'August'
                ],
                [
                    'September',
                    'September'
                ],
                [
                    'October',
                    'October'
                ],
                [
                    'November',
                    'November'
                ],
                [
                    'December',
                    'December'
                ]
            ]
        }, cfg)]);
    }
});