/*
 * File: app/store/SaccoContributionStore.js
 * Date: Wed Sep 30 2020 14:12:35 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.store.SaccoContributionStore', {
    extend: 'Ext.data.Store',
    alias: 'store.saccocontributionstore',

    requires: [
        'PayrollApp.model.SaccoContributions',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'SaccoContributionStore',
            autoLoad: true,
            model: 'PayrollApp.model.SaccoContributions',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getSaccoReport',
                reader: {
                    type: 'json',
                    rootProperty: 'saccosavings'
                }
            }
        }, cfg)]);
    }
});