/*
 * File: app/store/WelfareStore.js
 * Date: Thu Aug 27 2015 10:33:54 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.store.WelfareStore', {
    extend: 'Ext.data.Store',
    alias: 'store.welfarestore',

    requires: [
        'PayrollApp.model.WelfareContributions',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'PayrollApp.model.WelfareContributions',
            storeId: 'WelfareStore',
            proxy: {
                type: 'ajax',
                url: 'data/getDataFunctions.php?task=getWelfareReport',
                reader: {
                    type: 'json',
                    root: 'welfareSavings'
                }
            }
        }, cfg)]);
    }
});