/*
 * File: app/view/BankBranches.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.BankBranches', {
    extend: 'Ext.form.Panel',
    alias: 'widget.bankbranches',

    requires: [
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    frame: true,
    height: 446,
    width: 810,
    layout: 'absolute',
    url: 'data/updateFunctions.php?task=updateItems',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'data/updateFunctions.php?task=updateItems'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 10,
                    itemId: 'DeptName',
                    width: 180,
                    fieldLabel: 'ID',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'ID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 35,
                    itemId: 'DeptName1',
                    width: 350,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Branch Name',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'BankBranch',
                    allowBlank: false
                },
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 110,
                    height: 325,
                    itemId: 'bankBranchesGrid',
                    width: 800,
                    title: 'Benk Branches List',
                    store: 'BankBrancheStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'BankBrancheStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 187,
                            dataIndex: 'BankBranch',
                            text: 'BankBranch'
                        },
                        {
                            xtype: 'actioncolumn',
                            id: 'deleteBankBranch',
                            align: 'center',
                            text: 'Delete',
                            icon: 'icons/delete1.jpg',
                            items: [
                                {
                                    altText: 'Delete',
                                    icon: 'icons/delete1.jpg',
                                    tooltip: 'Delete Bank branch'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 155,
                    y: 65,
                    height: 35,
                    itemId: 'cmdNew',
                    width: 101,
                    text: '<b>New</b>'
                },
                {
                    xtype: 'button',
                    x: 280,
                    y: 65,
                    height: 35,
                    itemId: 'cmdSaveBankBranches',
                    width: 101,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 600,
                    y: 65,
                    height: 35,
                    itemId: 'cmdClose',
                    width: 101,
                    text: '<b>Close</b>'
                },
                {
                    xtype: 'textfield',
                    x: 570,
                    y: 5,
                    name: 'formStatus',
                    readOnly: true
                }
            ]
        });

        me.callParent(arguments);
    }

});