/*
 * File: app/view/BankLoansWin.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.BankLoansWin', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bankloanswin',

    requires: [
        'PayrollApp.view.BankLoansWinViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'bankloanswin'
    },
    frame: true,
    height: 216,
    width: 423,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 0,
            y: 20,
            itemId: 'payMonth',
            width: 320,
            fieldLabel: 'Payroll Month',
            labelAlign: 'right',
            displayField: 'month',
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: -2,
            y: 55,
            itemId: 'payType',
            width: 320,
            fieldLabel: 'Pay Type',
            labelAlign: 'right',
            displayField: 'PayType',
            store: 'PayTypeStore',
            valueField: 'ID'
        },
        {
            xtype: 'button',
            x: 20,
            y: 100,
            height: 40,
            itemId: 'cmdPreviewEarnDead',
            width: 105,
            text: '<b>Preview Report'
        },
        {
            xtype: 'button',
            x: 285,
            y: 100,
            height: 40,
            itemId: 'cmdExportEarnings',
            width: 115,
            text: '<b>Export Report'
        },
        {
            xtype: 'button',
            x: 150,
            y: 100,
            height: 40,
            itemId: 'cmdPrintBankLoans',
            width: 115,
            text: '<b>Print Report'
        },
        {
            xtype: 'button',
            x: 265,
            y: 160,
            height: 40,
            itemId: 'cmdClose',
            width: 150,
            text: '<b>Close'
        }
    ]

});