/*
 * File: app/view/BankPayments.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.BankPayments', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bankpayments',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    frame: true,
    height: 222,
    width: 348,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: -11,
                    y: 30,
                    itemId: 'payMonth',
                    width: 310,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    displayField: 'month',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'month'
                },
                {
                    xtype: 'combobox',
                    x: -11,
                    y: 90,
                    itemId: 'branch',
                    width: 310,
                    fieldLabel: 'Bank Branch',
                    labelAlign: 'right',
                    displayField: 'BankBranch',
                    queryMode: 'local',
                    store: 'BankBrancheStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: -11,
                    y: 60,
                    itemId: 'bankcode',
                    width: 310,
                    fieldLabel: 'Bank Name',
                    labelAlign: 'right',
                    displayField: 'BankName',
                    queryMode: 'local',
                    store: 'BankStore',
                    typeAhead: true,
                    valueField: 'BankCode'
                },
                {
                    xtype: 'button',
                    x: 20,
                    y: 160,
                    height: 40,
                    itemId: 'cmdBankPayments',
                    width: 90,
                    text: '<b>Open Report</b>'
                },
                {
                    xtype: 'button',
                    x: 120,
                    y: 160,
                    height: 40,
                    itemId: 'cmdExportBankPayments',
                    width: 90,
                    text: '<b>Export Report</b>'
                },
                {
                    xtype: 'button',
                    x: 220,
                    y: 160,
                    height: 40,
                    itemId: 'cmdClose',
                    width: 100,
                    text: '<b>Close</b>'
                }
            ]
        });

        me.callParent(arguments);
    }

});