/*
 * File: app/view/Banks.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.Banks', {
    extend: 'Ext.form.Panel',
    alias: 'widget.banks',

    requires: [
        'PayrollApp.view.BanksViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'banks'
    },
    frame: true,
    height: 542,
    width: 836,
    layout: 'absolute',
    frameHeader: false,
    header: false,
    url: 'data/updateFunctions.php?task=updateItems',

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'gridpanel',
                        x: 0,
                        y: 125,
                        height: 414,
                        itemId: 'banksGrid',
                        title: 'Banks',
                        store: 'BankStore',
                        selModel: Ext.create('Ext.selection.RowModel', {
                            selType: 'rowmodel'
                        }),
                        plugins: [
                            Ext.create('Ext.grid.plugin.RowEditing', {

                            })
                        ],
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'ID',
                                text: 'ID'
                            },
                            {
                                xtype: 'gridcolumn',
                                dataIndex: 'BankCode',
                                text: 'BankCode'
                            },
                            {
                                xtype: 'gridcolumn',
                                width: 200,
                                dataIndex: 'BankName',
                                text: 'BankName'
                            },
                            {
                                xtype: 'actioncolumn',
                                id: 'deleteBank',
                                width: 56,
                                align: 'center',
                                text: 'Delete',
                                items: [
                                    {
                                        altText: 'Delete',
                                        icon: 'icons/delete1.jpg',
                                        tooltip: 'Delete Bank'
                                    }
                                ]
                            }
                        ],
                        dockedItems: [
                            {
                                xtype: 'pagingtoolbar',
                                dock: 'bottom',
                                width: 360,
                                displayInfo: true,
                                store: 'BankStore'
                            }
                        ]
                    },
                    {
                        xtype: 'textfield',
                        x: -4,
                        y: 45,
                        width: 240,
                        fieldLabel: 'Bank Code',
                        labelAlign: 'right',
                        name: 'BankCode'
                    },
                    {
                        xtype: 'textfield',
                        x: -4,
                        y: 10,
                        width: 160,
                        fieldLabel: 'ID',
                        labelAlign: 'right',
                        name: 'ID',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        x: -3,
                        y: 80,
                        width: 380,
                        fieldLabel: 'Bank Name',
                        labelAlign: 'right',
                        name: 'BankName'
                    },
                    {
                        xtype: 'button',
                        x: 660,
                        y: 70,
                        height: 35,
                        itemId: 'cmdClose',
                        width: 105,
                        text: '<b>Close</b>'
                    },
                    {
                        xtype: 'button',
                        x: 540,
                        y: 70,
                        height: 35,
                        itemId: 'cmdSaveBanks',
                        width: 105,
                        text: '<b>Save</b>'
                    },
                    {
                        xtype: 'button',
                        x: 425,
                        y: 70,
                        height: 35,
                        itemId: 'cmdNew',
                        width: 105,
                        text: '<b>New</b>'
                    },
                    {
                        xtype: 'textfield',
                        x: 605,
                        y: 10,
                        name: 'formStatus',
                        readOnly: true
                    }
                ]
            };
        if (instanceConfig) {
            me.self.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    }

});