/*
 * File: app/view/Departments.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.Departments', {
    extend: 'Ext.form.Panel',
    alias: 'widget.departmentsform',

    requires: [
        'PayrollApp.view.DepartmentsViewModel',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'departmentsform'
    },
    frame: true,
    height: 505,
    width: 810,
    layout: 'absolute',
    url: 'data/updateFunctions.php?task=updateItems',

    items: [
        {
            xtype: 'textfield',
            x: 15,
            y: 40,
            itemId: 'DeptName',
            tabIndex: 1,
            width: 350,
            afterLabelTextTpl: [
                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
            ],
            fieldLabel: 'Department Name',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'deptName',
            allowBlank: false
        },
        {
            xtype: 'textfield',
            x: 15,
            y: 5,
            itemId: 'DeptName1',
            width: 165,
            fieldLabel: 'ID',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'ID',
            readOnly: true
        },
        {
            xtype: 'combobox',
            x: 15,
            y: 75,
            itemId: 'BranchID',
            tabIndex: 2,
            afterLabelTextTpl: [
                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
            ],
            fieldLabel: 'Branch',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'BranchID',
            allowBlank: false,
            displayField: 'BranchName',
            store: 'PayBranchStore',
            valueField: 'ID'
        },
        {
            xtype: 'textfield',
            x: 15,
            y: 110,
            itemId: 'Gl_acc',
            tabIndex: 3,
            fieldLabel: 'GL Account',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'gl_acc'
        },
        {
            xtype: 'gridpanel',
            x: 0,
            y: 155,
            height: 355,
            itemId: 'deptsGrid',
            width: 800,
            title: 'Department List',
            store: 'PayDeptStore',
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PayDeptStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 48,
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 176,
                    dataIndex: 'deptName',
                    text: 'DeptName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'BranchID',
                    text: 'BranchID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'gl_acc',
                    text: 'Gl_acc'
                },
                {
                    xtype: 'actioncolumn',
                    draggable: false,
                    id: 'deleteDept',
                    width: 53,
                    align: 'center',
                    menuText: 'Delete',
                    text: 'Delete',
                    tooltipType: 'title',
                    altText: 'Delete',
                    items: [
                        {
                            altText: 'Delete',
                            icon: 'icons/delete1.jpg',
                            tooltip: 'Delete Department'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            x: 390,
            y: 105,
            height: 30,
            itemId: 'cmdSaveDepartments',
            tabIndex: 4,
            width: 101,
            text: '<b>Save</b>'
        },
        {
            xtype: 'button',
            x: 500,
            y: 105,
            height: 30,
            itemId: 'cmdNew',
            tabIndex: 5,
            width: 101,
            text: '<b>New</b>'
        },
        {
            xtype: 'button',
            x: 615,
            y: 105,
            height: 30,
            itemId: 'cmdClose',
            tabIndex: 6,
            width: 101,
            text: '<b>Close</b>'
        },
        {
            xtype: 'textfield',
            x: 522,
            y: 26,
            name: 'formStatus',
            readOnly: true
        }
    ]

});