/*
 * File: app/view/EarningsDeductionsWindow.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EarningsDeductionsWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.earningsdeductionswindow',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    frame: true,
    height: 216,
    width: 423,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 20,
                    itemId: 'payMonth',
                    width: 320,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    displayField: 'month',
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 50,
                    itemId: 'payType',
                    width: 320,
                    fieldLabel: 'Pay Type',
                    labelAlign: 'right',
                    displayField: 'CatName',
                    store: 'PayCategoryStore',
                    valueField: 'CatName'
                },
                {
                    xtype: 'button',
                    x: 20,
                    y: 100,
                    height: 40,
                    itemId: 'cmdPreviewEarnDead',
                    width: 105,
                    text: '<b>Preview Report'
                },
                {
                    xtype: 'button',
                    x: 285,
                    y: 100,
                    height: 40,
                    itemId: 'cmdExportEarnings',
                    width: 115,
                    text: '<b>Export Report'
                },
                {
                    xtype: 'button',
                    x: 150,
                    y: 100,
                    height: 40,
                    itemId: 'cmdPrintdeptReport',
                    width: 115,
                    text: '<b>Print Report'
                },
                {
                    xtype: 'button',
                    x: 265,
                    y: 160,
                    height: 40,
                    itemId: 'cmdClose',
                    width: 150,
                    text: '<b>Close'
                }
            ]
        });

        me.callParent(arguments);
    }

});