/*
 * File: app/view/EarningsDeductionsWindow.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EarningsDeductionsWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.earningsdeductionswindow',

    requires: [
        'PayrollApp.view.EarningsDeductionsWindowViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'earningsdeductionswindow'
    },
    frame: true,
    height: 182,
    width: 394,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 0,
            y: 5,
            itemId: 'payMonth',
            width: 270,
            fieldLabel: 'Payroll Month',
            labelAlign: 'right',
            displayField: 'Month',
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: -2,
            y: 40,
            itemId: 'payType',
            width: 270,
            fieldLabel: 'Pay Type',
            labelAlign: 'right',
            displayField: 'CatName',
            store: 'PayCategoryStore',
            valueField: 'CatName'
        },
        {
            xtype: 'button',
            x: 10,
            y: 85,
            height: 40,
            itemId: 'cmdPreviewEarnDead',
            width: 120,
            text: '<b>Preview Report'
        },
        {
            xtype: 'button',
            x: 265,
            y: 85,
            height: 40,
            itemId: 'cmdExportEarnings',
            width: 115,
            text: '<b>Export Report'
        },
        {
            xtype: 'button',
            x: 145,
            y: 85,
            height: 40,
            itemId: 'cmdPrintdeptReport',
            width: 115,
            text: '<b>Print Report'
        },
        {
            xtype: 'button',
            x: 265,
            y: 130,
            height: 40,
            itemId: 'cmdClose',
            width: 115,
            text: '<b>Close'
        }
    ]

});