/*
 * File: app/view/EarningsGrid.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EarningsGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.earningsgrid',

    requires: [
        'PayrollApp.view.EarningsGridViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'earningsgrid'
    },
    height: 650,
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'Earnings Report',
    columnLines: true,
    store: 'EarningStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'PayrollPostingStore'
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 43,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'combobox',
                    x: -9,
                    y: 5,
                    itemId: 'PaymentType',
                    width: 324,
                    fieldLabel: 'Pay Type',
                    labelAlign: 'right',
                    displayField: 'PayType',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayTypeStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'button',
                    x: 860,
                    y: 5,
                    height: 35,
                    width: 117,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 985,
                    y: 5,
                    height: 35,
                    itemId: 'cmdExportEarnings',
                    width: 129,
                    text: '<b>Export to Excel</b>'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 53,
            dataIndex: 'PID',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 224,
            dataIndex: 'EmpNames',
            text: 'EmpNames'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Category',
            text: 'CatID'
        },
        {
            xtype: 'gridcolumn',
            width: 171,
            dataIndex: 'PayType',
            text: 'PayType'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Amount',
            text: 'Amount'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Balance',
            text: 'Balance'
        }
    ]

});