/*
 * File: app/view/EmployeeRegister.js
 * Date: Tue Mar 31 2015 14:16:55 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EmployeeRegister', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.employeeregister',

    requires: [
        'Ext.grid.View',
        'Ext.form.field.Text',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column'
    ],

    height: 693,
    autoScroll: true,
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'Employees Register',
    columnLines: true,
    store: 'EmpRegisterStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {
                autoScroll: false
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            width: 235,
                            fieldLabel: '',
                            emptyText: 'Search by Pid, Names, Department, Job Title'
                        },
                        {
                            xtype: 'button',
                            width: 96,
                            text: '<b>Search</b>'
                        },
                        {
                            xtype: 'tbspacer',
                            height: 14,
                            width: 67
                        },
                        {
                            xtype: 'button',
                            itemId: 'cmdNewEmployee',
                            width: 92,
                            text: '<b>New Employee</b>'
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'EmpRegisterStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PID',
                    text: 'PID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'FirstName',
                    text: 'FirstName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'LastName',
                    text: 'LastName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SurName',
                    text: 'SurName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Department',
                    text: 'Department'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JobTitle',
                    text: 'JobTitle'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Box',
                    text: 'Box'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'PostalCode',
                    text: 'PostalCode'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Phone',
                    text: 'Phone'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Town',
                    text: 'Town'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Email',
                    text: 'Email'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ID_No',
                    text: 'ID_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Pin_No',
                    text: 'Pin_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'NSSF_No',
                    text: 'NSSF_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'NHIF_No',
                    text: 'NHIF_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Account_No',
                    text: 'Account_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EmpType',
                    text: 'EmpType'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'AppointDate',
                    text: 'AppointDate'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'AppointEndDate',
                    text: 'AppointEndDate'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ConfirmDate',
                    text: 'ConfirmDate'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Nationality',
                    text: 'Nationality'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'MaritalStatus',
                    text: 'MaritalStatus'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'DOB',
                    text: 'DOB'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Sex',
                    text: 'Sex'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'BankID',
                    text: 'BankID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'BranchID',
                    text: 'BranchID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EmpBranch',
                    text: 'EmpBranch'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'JobGroup',
                    text: 'JobGroup'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Taxable',
                    text: 'Taxable'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Pensionable',
                    text: 'Pensionable'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Unionisable',
                    text: 'Unionisable'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Housed',
                    text: 'Housed'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'NSSF',
                    text: 'NSSF'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'NHIF',
                    text: 'NHIF'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EmpStatus',
                    text: 'EmpStatus'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'GratuityRates',
                    text: 'GratuityRates'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'HELB_No',
                    text: 'HELB_No'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'SaccoNo',
                    text: 'SaccoNo'
                }
            ]
        });

        me.callParent(arguments);
    }

});