/*
 * File: app/view/EmpPayments.js
 * Date: Mon Apr 13 2015 09:29:48 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EmpPayments', {
    extend: 'Ext.form.Panel',
    alias: 'widget.emppayments',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Action',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.Checkbox'
    ],

    height: 693,
    layout: 'absolute',
    closable: true,
    collapsed: false,
    collapsible: true,
    title: 'Employee Payments',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 0,
                    height: 660,
                    itemId: 'employeelistGrid',
                    width: 390,
                    title: 'Employee List',
                    columnLines: true,
                    store: 'EmployeeListStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'EmployeeListStore'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            height: 26,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'txtSearch',
                                    width: 205,
                                    emptyText: 'Search via PID,FirstName,LastName,Surnamr'
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cmdSearchEmpPayments',
                                    text: '<b>Search</b>'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 61,
                            dataIndex: 'PID',
                            text: 'PID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'FirstName',
                            text: 'FirstName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'LastName',
                            text: 'LastName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'SurName',
                            text: 'SurName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Department',
                            text: 'Department'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'JobTitle',
                            text: 'JobTitle'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'JobGroup',
                            text: 'JobGroup'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Taxable',
                            text: 'Taxable'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Pensionable',
                            text: 'Pensionable'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Unionisable',
                            text: 'Unionisable'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Housed',
                            text: 'Housed'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'NSSF',
                            text: 'NSSF'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'NHIF',
                            text: 'NHIF'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    x: 400,
                    y: 185,
                    height: 475,
                    itemId: 'paydeductgrid',
                    title: 'Employee Payments and Deductions',
                    columnLines: true,
                    store: 'EmpPaymentStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top'
                        },
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'EmpPaymentStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 43,
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 50,
                            dataIndex: 'PID',
                            text: 'PID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'PayType',
                            text: 'PayType'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 166,
                            dataIndex: 'PayName',
                            text: 'PayName',
                            editor: {
                                xtype: 'combobox',
                                displayField: 'PayType',
                                minChars: 2,
                                queryMode: 'local',
                                store: 'PayTypeStore',
                                typeAhead: true,
                                valueField: 'CatID'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Amount',
                            text: 'Amount',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Balance',
                            text: 'Balance',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            id: 'delete',
                            itemId: '',
                            width: 80,
                            align: 'center',
                            text: 'Delete',
                            icon: '../icons/delete1.jpg',
                            items: [
                                {
                                    icon: 'icons/delete2.jpg',
                                    iconCls: 'text-align: center;'
                                }
                            ]
                        }
                    ],
                    selModel: Ext.create('Ext.selection.RowModel', {

                    }),
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ]
                },
                {
                    xtype: 'fieldset',
                    x: 400,
                    y: 0,
                    formBind: false,
                    frame: false,
                    height: 180,
                    layout: 'absolute',
                    collapsible: true,
                    title: '<b>Employee Details</b>',
                    items: [
                        {
                            xtype: 'displayfield',
                            x: -33,
                            y: -1,
                            itemId: 'pid',
                            fieldLabel: 'PID',
                            labelAlign: 'right',
                            name: 'PID',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -28,
                            y: 125,
                            fieldLabel: 'Job Group',
                            labelAlign: 'right',
                            name: 'JobGroup',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -29,
                            y: 105,
                            fieldLabel: 'Job Title',
                            labelAlign: 'right',
                            name: 'JobTitle',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -29,
                            y: 85,
                            fieldLabel: 'Departmant',
                            labelAlign: 'right',
                            name: 'Department',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -30,
                            y: 65,
                            fieldLabel: 'Surname',
                            labelAlign: 'right',
                            name: 'SurName',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -31,
                            y: 45,
                            fieldLabel: 'Last Name',
                            labelAlign: 'right',
                            name: 'LastName',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            x: -31,
                            y: 20,
                            shadow: true,
                            fieldLabel: 'First Name',
                            labelAlign: 'right',
                            name: 'FirstName',
                            fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 0,
                            name: 'Taxable',
                            readOnly: true,
                            boxLabel: 'Taxable',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 125,
                            name: 'NHIF',
                            readOnly: true,
                            boxLabel: 'NHIF',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 100,
                            name: 'NSSF',
                            readOnly: true,
                            boxLabel: 'NSSF',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 75,
                            name: 'Housed',
                            readOnly: true,
                            boxLabel: 'Housed',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 50,
                            name: 'Unionisable',
                            readOnly: true,
                            boxLabel: 'Unionisable',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 240,
                            y: 25,
                            name: 'Pensionable',
                            readOnly: true,
                            boxLabel: 'Pensionable',
                            inputValue: 'Yes',
                            uncheckedValue: 'No'
                        },
                        {
                            xtype: 'button',
                            x: 360,
                            y: 0,
                            height: 35,
                            itemId: 'cmdPostByPid',
                            width: 145,
                            text: '<b>Post By PID</b>'
                        },
                        {
                            xtype: 'button',
                            x: 360,
                            y: 80,
                            height: 35,
                            itemId: 'cmdClose',
                            width: 145,
                            text: '<b>Close</b>'
                        },
                        {
                            xtype: 'button',
                            x: 360,
                            y: 40,
                            height: 35,
                            itemId: 'cmdPostByCode',
                            width: 145,
                            text: '<b>Post By Code</b>'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});