/*
 * File: app/view/EmpPayments.js
 * Date: Fri Aug 25 2023 12:57:30 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.EmpPayments', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.emppayments',

    requires: [
        'PayrollApp.view.EmpPaymentsViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Display',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Action',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing'
    ],

    viewModel: {
        type: 'emppayments'
    },
    alignOnScroll: false,
    title: 'Employee Earnings and Deductions',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'container',
                        flex: 1,
                        border: 2,
                        frame: true,
                        margin: '0 5 0 0',
                        width: 404,
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'gridpanel',
                                frame: true,
                                itemId: 'employeelistGrid',
                                scrollable: 'both',
                                ui: 'default-framed',
                                width: 390,
                                bodyBorder: true,
                                manageHeight: false,
                                columnLines: true,
                                store: 'EmployeeListStore',
                                dockedItems: [
                                    {
                                        xtype: 'pagingtoolbar',
                                        dock: 'bottom',
                                        width: 360,
                                        displayInfo: true,
                                        store: 'EmployeeListStore'
                                    },
                                    {
                                        xtype: 'container',
                                        dock: 'top',
                                        height: 43,
                                        width: 100,
                                        layout: 'absolute',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                x: 5,
                                                y: 5,
                                                itemId: 'txtSearch',
                                                width: 205,
                                                emptyText: 'Search via PID,FirstName,LastName,Surnamr'
                                            },
                                            {
                                                xtype: 'button',
                                                x: 290,
                                                y: 5,
                                                itemId: 'cmdSearchEmpPayments',
                                                text: '<b>Search</b>'
                                            }
                                        ]
                                    }
                                ],
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        width: 61,
                                        dataIndex: 'PID',
                                        text: 'PID'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'FirstName',
                                        text: 'FirstName'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'LastName',
                                        text: 'LastName'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'SurName',
                                        text: 'SurName'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Department',
                                        text: 'Department'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'JobTitle',
                                        text: 'JobTitle'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'JobGroup',
                                        text: 'JobGroup'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Taxable',
                                        text: 'Taxable'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Pensionable',
                                        text: 'Pensionable'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Unionisable',
                                        text: 'Unionisable'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Housed',
                                        text: 'Housed'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'NSSF',
                                        text: 'NSSF'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'NHIF',
                                        text: 'NHIF'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 2,
                        border: true,
                        frame: true,
                        items: [
                            {
                                xtype: 'fieldset',
                                frame: false,
                                height: 210,
                                padding: '0 0 0 0',
                                layout: 'absolute',
                                title: 'Employee Details',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: -1,
                                        itemId: 'pid',
                                        fieldLabel: 'PID',
                                        labelAlign: 'right',
                                        name: 'PID',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 125,
                                        fieldLabel: 'Job Group',
                                        labelAlign: 'right',
                                        name: 'JobGroup',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 105,
                                        fieldLabel: 'Job Title',
                                        labelAlign: 'right',
                                        name: 'JobTitle',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 85,
                                        fieldLabel: 'Departmant',
                                        labelAlign: 'right',
                                        name: 'Department',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 65,
                                        width: 130,
                                        fieldLabel: 'Surname',
                                        labelAlign: 'right',
                                        name: 'SurName',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 45,
                                        fieldLabel: 'Last Name',
                                        labelAlign: 'right',
                                        name: 'LastName',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        x: 0,
                                        y: 20,
                                        shadow: true,
                                        fieldLabel: 'First Name',
                                        labelAlign: 'right',
                                        name: 'FirstName',
                                        fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 0,
                                        name: 'Taxable',
                                        readOnly: true,
                                        boxLabel: 'Taxable',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 125,
                                        name: 'NHIF',
                                        readOnly: true,
                                        boxLabel: 'NHIF',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 100,
                                        name: 'NSSF',
                                        readOnly: true,
                                        boxLabel: 'NSSF',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 75,
                                        name: 'Housed',
                                        readOnly: true,
                                        boxLabel: 'Housed',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 50,
                                        name: 'Unionisable',
                                        readOnly: true,
                                        boxLabel: 'Unionisable',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        x: 470,
                                        y: 25,
                                        name: 'Pensionable',
                                        readOnly: true,
                                        boxLabel: 'Pensionable',
                                        inputValue: 'Yes',
                                        uncheckedValue: 'No'
                                    },
                                    {
                                        xtype: 'button',
                                        x: 590,
                                        y: 0,
                                        height: 35,
                                        itemId: 'cmdPostByPid',
                                        width: 161,
                                        iconCls: 'x-fa fa-pencil-square-o',
                                        text: '<b>Post By PID</b>'
                                    },
                                    {
                                        xtype: 'button',
                                        x: 590,
                                        y: 80,
                                        height: 35,
                                        itemId: 'cmdOpenImportWin',
                                        width: 161,
                                        iconCls: 'x-fa fa-upload',
                                        text: '<b>Import from Excel</b>'
                                    },
                                    {
                                        xtype: 'button',
                                        x: 590,
                                        y: 40,
                                        height: 35,
                                        itemId: 'cmdPostByCode',
                                        width: 161,
                                        iconCls: 'x-fa fa-plus',
                                        text: '<b>Post By Code</b>'
                                    }
                                ]
                            },
                            {
                                xtype: 'gridpanel',
                                itemId: 'paydeductgrid',
                                scrollable: 'both',
                                title: 'Employee Payments and Deductions',
                                columnLines: true,
                                store: 'EmpPaymentsStore',
                                columns: [
                                    {
                                        xtype: 'gridcolumn',
                                        width: 43,
                                        dataIndex: 'ID',
                                        text: 'ID'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        width: 50,
                                        dataIndex: 'PID',
                                        text: 'PID'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'PayType',
                                        text: 'PayType'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        width: 166,
                                        dataIndex: 'PayName',
                                        text: 'PayName',
                                        editor: {
                                            xtype: 'combobox',
                                            displayField: 'PayType',
                                            minChars: 2,
                                            queryMode: 'local',
                                            store: 'PayTypeStore',
                                            typeAhead: true,
                                            valueField: 'CatID'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Amount',
                                        text: 'Amount',
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        dataIndex: 'Balance',
                                        text: 'Balance',
                                        editor: {
                                            xtype: 'textfield'
                                        }
                                    },
                                    {
                                        xtype: 'actioncolumn',
                                        id: 'delete',
                                        width: 80,
                                        align: 'center',
                                        text: 'Delete',
                                        icon: '../icons/delete1.jpg',
                                        items: [
                                            {
                                                icon: 'icons/delete2.jpg',
                                                iconCls: 'text-align: center;'
                                            }
                                        ]
                                    }
                                ],
                                selModel: Ext.create('Ext.selection.RowModel', {
                                    selType: 'rowmodel'
                                }),
                                plugins: [
                                    Ext.create('Ext.grid.plugin.RowEditing', {

                                    })
                                ],
                                dockedItems: [
                                    {
                                        xtype: 'pagingtoolbar',
                                        dock: 'bottom',
                                        width: 360,
                                        displayInfo: true,
                                        store: 'EmpPaymentsStore'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.self.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    }

});