/*
 * File: app/view/ImportPayments.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.ImportPayments', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.importpayments',

    requires: [
        'PayrollApp.view.ImportPaymentsViewModel',
        'Ext.form.field.ComboBox',
        'Ext.form.FieldContainer',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'importpayments'
    },
    height: 146,
    width: 332,
    bodyPadding: 10,

    items: [
        {
            xtype: 'combobox',
            fieldLabel: 'Payment Type',
            labelAlign: 'right',
            displayField: 'CatName',
            minChars: 2,
            queryMode: 'local',
            store: 'PayCategoryStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            fieldLabel: 'Payment',
            labelAlign: 'right',
            displayField: 'PayType',
            minChars: 2,
            queryMode: 'local',
            store: 'PayTypeStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'fieldcontainer',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'cmdImportPayments',
                    margin: '0 50 0 30',
                    width: 98,
                    iconCls: 'x-fa fa-upload',
                    text: 'Import'
                },
                {
                    xtype: 'button',
                    itemId: 'cmdClose',
                    width: 109,
                    iconCls: 'x-fa fa-close',
                    text: 'Cancel'
                }
            ]
        }
    ]

});