/*
 * File: app/view/JobGroups.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.JobGroups', {
    extend: 'Ext.form.Panel',
    alias: 'widget.jobgroups',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    draggable: true,
    frame: true,
    height: 565,
    width: 850,
    layout: 'absolute',
    header: false,
    simpleDrag: true,
    url: 'data/updateFunctions.php?task=updateItems',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'data/updateFunctions.php?task=updateItems'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 140,
                    height: 414,
                    itemId: 'jobGroupsGrid',
                    title: 'groups list',
                    store: 'JobGroupStore',
                    selModel: Ext.create('Ext.selection.RowModel', {

                    }),
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'JobGroupStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'groupID',
                            text: 'GroupID',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'groupName',
                            text: 'GroupName',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'houseAllowance',
                            text: 'HouseAllowance',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'leaveAllowance',
                            text: 'LeaveAllowance',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'actioncolumn',
                            id: 'deleteJobgroup',
                            width: 60,
                            align: 'center',
                            text: 'Delete',
                            items: [
                                {
                                    icon: 'icons/delete1.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 30,
                    width: 180,
                    fieldLabel: 'Group ID',
                    labelAlign: 'right',
                    name: 'groupID'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 5,
                    width: 180,
                    fieldLabel: 'ID',
                    labelAlign: 'right',
                    name: 'ID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 55,
                    width: 265,
                    fieldLabel: 'Group Name',
                    labelAlign: 'right',
                    name: 'groupName'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 80,
                    width: 265,
                    fieldLabel: 'House Allowance',
                    labelAlign: 'right',
                    name: 'houseAllowance'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 105,
                    width: 265,
                    fieldLabel: 'Leave Allowance',
                    labelAlign: 'right',
                    name: 'leaveAllowance'
                },
                {
                    xtype: 'button',
                    x: 505,
                    y: 90,
                    height: 35,
                    itemId: 'cmdSaveGroups',
                    width: 105,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 380,
                    y: 90,
                    height: 35,
                    itemId: 'cmdNew',
                    width: 105,
                    text: '<b>New</b>'
                },
                {
                    xtype: 'button',
                    x: 700,
                    y: 90,
                    height: 35,
                    itemId: 'cmdClose',
                    width: 105,
                    text: '<b>Close</b>'
                },
                {
                    xtype: 'textfield',
                    x: 695,
                    y: 35,
                    width: 110,
                    name: 'formStatus',
                    readOnly: true
                }
            ]
        });

        me.callParent(arguments);
    }

});