/*
 * File: app/view/JobTitles.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.JobTitles', {
    extend: 'Ext.form.Panel',
    alias: 'widget.jobtitles',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.selection.RowModel',
        'Ext.grid.plugin.RowEditing',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    draggable: true,
    frame: true,
    height: 541,
    padding: '0 0 0 0',
    width: 850,
    layout: 'absolute',
    bodyPadding: 0,
    header: false,
    simpleDrag: true,
    url: 'data/updateFunctions.php?task=updateItems',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'data/updateFunctions.php?task=updateItems'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 100,
                    height: 440,
                    itemId: 'jobTitlesGrid',
                    width: 848,
                    title: 'Titles',
                    store: 'JobTitlesStore',
                    selModel: Ext.create('Ext.selection.RowModel', {

                    }),
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {

                        })
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'JobTitlesStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 173,
                            dataIndex: 'JobTitle',
                            text: 'JobTitle'
                        },
                        {
                            xtype: 'actioncolumn',
                            id: 'deleteJobtitle',
                            width: 46,
                            align: 'center',
                            text: 'Delete',
                            items: [
                                {
                                    icon: 'icons/delete1.jpg'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 35,
                    width: 380,
                    fieldLabel: 'Title Name',
                    labelAlign: 'right',
                    name: 'JobTitle'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 10,
                    width: 170,
                    fieldLabel: 'ID',
                    labelAlign: 'right',
                    name: 'ID',
                    readOnly: true
                },
                {
                    xtype: 'button',
                    x: 710,
                    y: 50,
                    height: 35,
                    itemId: 'cmdClose',
                    width: 105,
                    text: '<b>Close</b>'
                },
                {
                    xtype: 'button',
                    x: 520,
                    y: 50,
                    height: 35,
                    itemId: 'cmdSaveTitles',
                    width: 105,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 410,
                    y: 50,
                    height: 35,
                    itemId: 'cmdNew',
                    width: 105,
                    text: '<b>New</b>'
                },
                {
                    xtype: 'textfield',
                    x: 705,
                    y: 10,
                    width: 110,
                    name: 'formStatus',
                    readOnly: true
                }
            ]
        });

        me.callParent(arguments);
    }

});