/*
 * File: app/view/LoginMain.js
 * Date: Fri Aug 25 2023 10:51:36 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.LoginMain', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.loginMain',

    requires: [
        'PayrollApp.view.LoginMainViewModel',
        'Ext.panel.Panel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.Img',
        'Ext.form.field.Display'
    ],

    viewModel: {
        type: 'loginMain'
    },
    layout: 'center',

    items: [
        {
            xtype: 'panel',
            height: 289,
            width: 454,
            layout: 'absolute',
            items: [
                {
                    xtype: 'textfield',
                    x: 130,
                    y: 70,
                    itemId: 'login-user',
                    width: 300,
                    fieldLabel: 'Username',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;'
                },
                {
                    xtype: 'textfield',
                    x: 130,
                    y: 110,
                    itemId: 'login-pwd',
                    width: 300,
                    fieldLabel: 'Password',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;',
                    inputType: 'password',
                    maxLength: 12,
                    minLength: 6
                },
                {
                    xtype: 'combobox',
                    x: 80,
                    y: 150,
                    itemId: 'login-period',
                    width: 350,
                    fieldLabel: 'Select a Different Period',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;',
                    labelWidth: 150,
                    displayField: 'Period',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PeriodsStore',
                    typeAhead: true,
                    valueField: 'Period'
                },
                {
                    xtype: 'button',
                    x: 170,
                    y: 210,
                    itemId: 'cmdLogin',
                    width: 80,
                    text: '<b>Login</b>'
                },
                {
                    xtype: 'button',
                    x: 300,
                    y: 210,
                    itemId: 'cmdCancel',
                    width: 80,
                    text: '<b>Cancel</b>'
                },
                {
                    xtype: 'image',
                    x: 10,
                    y: 5,
                    height: 120,
                    width: 135,
                    src: 'images/chmis.png'
                },
                {
                    xtype: 'displayfield',
                    x: 260,
                    y: 15,
                    value: 'Payroll Login',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'displayfield',
                    x: 125,
                    y: 245,
                    width: 300,
                    value: '© CHAK CHMIS 2023 All Rights Reserved'
                }
            ]
        }
    ]

});