/*
 * File: app/view/MembersEmails.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.MembersEmails', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.membersemails',

    requires: [
        'PayrollApp.view.MembersEmailsViewModel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.selection.CheckboxModel',
        'Ext.form.FieldContainer',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'membersemails'
    },
    height: 438,
    width: 591,
    columnLines: true,
    store: 'MemberEmailStore',

    columns: [
        {
            xtype: 'gridcolumn',
            width: 42,
            dataIndex: 'pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 79,
            dataIndex: 'firstname',
            text: 'Firstname'
        },
        {
            xtype: 'gridcolumn',
            width: 88,
            dataIndex: 'lastname',
            text: 'Lastname'
        },
        {
            xtype: 'gridcolumn',
            width: 94,
            dataIndex: 'surname',
            text: 'Surname'
        },
        {
            xtype: 'gridcolumn',
            width: 211,
            dataIndex: 'email',
            text: 'Email'
        }
    ],
    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'MemberEmailStore'
        },
        {
            xtype: 'fieldcontainer',
            dock: 'top',
            height: 39,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'button',
                    x: 215,
                    y: 5,
                    height: 30,
                    itemId: 'cmdSendEmails',
                    width: 175,
                    iconCls: 'x-fa fa-inbox',
                    text: 'Send Payslips'
                }
            ]
        }
    ],
    selModel: {
        selType: 'checkboxmodel'
    }

});