/*
 * File: app/view/MyForm1.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.MyForm1', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myform1',

    requires: [
        'PayrollApp.view.MyForm1ViewModel'
    ],

    viewModel: {
        type: 'myform1'
    },
    frame: true,
    height: 283,
    width: 409,
    bodyPadding: 10,
    title: 'Batch Posting'

});