/*
 * File: app/view/MyForm1.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.MyForm1', {
    extend: 'Ext.form.Panel',

    frame: true,
    height: 283,
    width: 409,
    bodyPadding: 10,
    title: 'Batch Posting',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});