/*
 * File: app/view/NewUserForm.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.NewUserForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.newuserform',

    requires: [
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.button.Button'
    ],

    frame: true,
    height: 250,
    itemId: 'myform1',
    width: 400,
    layout: 'absolute',
    bodyPadding: 10,
    url: 'data/manageUsers.php?task=updateUser',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'data/manageUsers.php?task=updateUser'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 5,
                    width: 155,
                    fieldLabel: 'ID',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'ID',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 30,
                    width: 290,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'First Name',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'FirstName',
                    tabIndex: 1,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 55,
                    width: 290,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Last Name',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'LastName',
                    tabIndex: 2,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 80,
                    width: 290,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Username',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'UserName',
                    tabIndex: 3,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 105,
                    width: 290,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Password',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'password1',
                    submitValue: false,
                    inputType: 'password',
                    tabIndex: 4,
                    allowBlank: false,
                    validateBlank: true
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 130,
                    width: 290,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Confirm Password',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'password2',
                    submitValue: false,
                    inputType: 'password',
                    tabIndex: 5,
                    allowBlank: false,
                    validateBlank: true
                },
                {
                    xtype: 'button',
                    x: 65,
                    y: 170,
                    height: 40,
                    itemId: 'cmdSaveUser',
                    width: 100,
                    tabIndex: 6,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 250,
                    y: 170,
                    height: 40,
                    itemId: 'cmdClose',
                    width: 100,
                    text: '<b>Cancel</b>'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 215,
                    hidden: true,
                    name: 'formStatus'
                }
            ]
        });

        me.callParent(arguments);
    }

});