/*
 * File: app/view/NssfReturns.js
 * Date: Wed Jul 14 2021 07:44:29 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.NssfReturns', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.nssfreturns',

    requires: [
        'PayrollApp.view.NssfReturnsViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'nssfreturns'
    },
    height: 577,
    itemId: 'nssfMonth',
    width: 1103,
    columnLines: true,
    store: 'NssfReturnsStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'NhifReturnsStore'
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 40,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 5,
                    itemId: 'nssfMonth',
                    width: 294,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    labelStyle: 'color:green; font-weight:bold;',
                    displayField: 'Month',
                    queryMode: 'local',
                    store: 'PayMonthsStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'button',
                    x: 485,
                    y: 5,
                    height: 31,
                    width: 164,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 670,
                    y: 5,
                    height: 30,
                    itemId: 'cmdExportNssf',
                    width: 145,
                    text: '<b>Export</b>'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 76,
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            width: 72,
            dataIndex: 'pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 202,
            dataIndex: 'empNames',
            text: 'Emp Names'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'pay_type',
            text: 'Pay Type'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Self',
            text: 'Self'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Company',
            text: 'Company'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Amount',
            text: 'Amount'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ID_No',
            text: 'Id No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'NSSFNo',
            text: 'Nssfno'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'payMonth',
            text: 'Pay Month'
        }
    ]

});