/*
 * File: app/view/P9ReportWindow.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.P9ReportWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.p9reportwindow',

    requires: [
        'PayrollApp.view.P9ReportWindowViewModel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'p9reportwindow'
    },
    frame: true,
    height: 216,
    width: 423,
    layout: 'absolute',

    items: [
        {
            xtype: 'textfield',
            x: -31,
            y: 30,
            itemId: 'pid',
            width: 320,
            fieldLabel: 'PID',
            labelAlign: 'right'
        },
        {
            xtype: 'button',
            x: 20,
            y: 100,
            height: 40,
            itemId: 'cmdPreviewP9',
            width: 105,
            text: '<b>Preview Report'
        },
        {
            xtype: 'button',
            x: 285,
            y: 100,
            height: 40,
            itemId: 'cmdPrintAll',
            width: 115,
            text: '<b>Print All'
        },
        {
            xtype: 'button',
            x: 150,
            y: 100,
            height: 40,
            itemId: 'cmdPrintP9',
            width: 115,
            text: '<b>Print Report'
        },
        {
            xtype: 'button',
            x: 265,
            y: 160,
            height: 40,
            itemId: 'cmdClose',
            width: 150,
            text: '<b>Close'
        }
    ]

});