/*
 * File: app/view/P9Report.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.P9Report', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.p9report',

    requires: [
        'PayrollApp.view.P9ReportViewModel',
        'Ext.form.Label',
        'Ext.form.field.Display',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging'
    ],

    viewModel: {
        type: 'p9report'
    },
    height: 650,
    layout: 'absolute',
    title: 'P9 Report',

    items: [
        {
            xtype: 'label',
            x: 315,
            y: 5,
            height: 20,
            width: 225,
            text: 'KENYA REVENUE AUTHORITY'
        },
        {
            xtype: 'displayfield',
            x: 30,
            y: 10,
            fieldLabel: 'Employers name',
            labelWidth: 120,
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            x: 30,
            y: 80,
            fieldLabel: 'Employers name',
            labelWidth: 120,
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            x: 525,
            y: 20,
            fieldLabel: 'Employer\'s Pin',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            x: 525,
            y: 70,
            fieldLabel: 'Employee\'s Pin',
            value: 'Display Field'
        },
        {
            xtype: 'displayfield',
            x: 30,
            y: 45,
            fieldLabel: 'Employers name',
            labelWidth: 120,
            value: 'Display Field'
        },
        {
            xtype: 'gridpanel',
            x: 0,
            y: 115,
            height: 510,
            store: 'P9ReportStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 40,
                    dataIndex: 'PID',
                    text: 'Pid'
                },
                {
                    xtype: 'gridcolumn',
                    width: 62,
                    dataIndex: 'payrollMonth',
                    text: 'PayMonth'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnA',
                    text: 'ColumnA'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnB',
                    text: 'ColumnB'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnC',
                    text: 'ColumnC'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnD',
                    text: 'ColumnD'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnE1',
                    text: 'ColumnE1'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnE2',
                    text: 'ColumnE2'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnE3',
                    text: 'ColumnE3'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnF',
                    text: 'ColumnF'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnG',
                    text: 'ColumnG'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnH',
                    text: 'ColumnH'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnJ',
                    text: 'ColumnJ'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnK',
                    text: 'ColumnK'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ColumnL',
                    text: 'ColumnL'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'P9ReportStore'
                }
            ]
        }
    ]

});