/*
 * File: app/view/PayeReturnsViewModel.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayeReturnsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.payereturns',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        payeReturns: {
            model: 'PayrollApp.model.PayeReturns',
            data: [
                {
                    ID: 'asperiores_01',
                    pid: 'possimus',
                    empNames: 'voluptates',
                    pay_type: 'velit',
                    Amount: 'voluptatem',
                    ID_No: 'velit',
                    PinNo: 'dolore',
                    payMonth: 'eos'
                },
                {
                    ID: 'consectetur_11',
                    pid: 'molestiae',
                    empNames: 'suscipit',
                    pay_type: 'eos',
                    Amount: 'nihil',
                    ID_No: 'ab',
                    PinNo: 'autem',
                    payMonth: 'quasi'
                },
                {
                    ID: 'voluptatibus_21',
                    pid: 'ut',
                    empNames: 'ut',
                    pay_type: 'alias',
                    Amount: 'maxime',
                    ID_No: 'consequatur',
                    PinNo: 'repellat',
                    payMonth: 'quisquam'
                },
                {
                    ID: 'placeat_31',
                    pid: 'voluptates',
                    empNames: 'dolorum',
                    pay_type: 'molestiae',
                    Amount: 'est',
                    ID_No: 'quos',
                    PinNo: 'quidem',
                    payMonth: 'aliquam'
                },
                {
                    ID: 'ducimus_41',
                    pid: 'distinctio',
                    empNames: 'molestiae',
                    pay_type: 'tenetur',
                    Amount: 'sed',
                    ID_No: 'voluptas',
                    PinNo: 'voluptates',
                    payMonth: 'dolor'
                },
                {
                    ID: 'quia_51',
                    pid: 'ad',
                    empNames: 'recusandae',
                    pay_type: 'eius',
                    Amount: 'sapiente',
                    ID_No: 'aperiam',
                    PinNo: 'occaecati',
                    payMonth: 'omnis'
                },
                {
                    ID: 'corporis_61',
                    pid: 'et',
                    empNames: 'et',
                    pay_type: 'eaque',
                    Amount: 'alias',
                    ID_No: 'inventore',
                    PinNo: 'earum',
                    payMonth: 'quia'
                },
                {
                    ID: 'iure_71',
                    pid: 'reiciendis',
                    empNames: 'atque',
                    pay_type: 'qui',
                    Amount: 'explicabo',
                    ID_No: 'et',
                    PinNo: 'quisquam',
                    payMonth: 'earum'
                },
                {
                    ID: 'et_81',
                    pid: 'quasi',
                    empNames: 'corrupti',
                    pay_type: 'ducimus',
                    Amount: 'corporis',
                    ID_No: 'iure',
                    PinNo: 'illum',
                    payMonth: 'omnis'
                },
                {
                    ID: 'quis_91',
                    pid: 'dolorem',
                    empNames: 'omnis',
                    pay_type: 'quibusdam',
                    Amount: 'voluptatem',
                    ID_No: 'voluptatem',
                    PinNo: 'quaerat',
                    payMonth: 'animi'
                },
                {
                    ID: 'sunt_101',
                    pid: 'nemo',
                    empNames: 'distinctio',
                    pay_type: 'id',
                    Amount: 'vel',
                    ID_No: 'id',
                    PinNo: 'explicabo',
                    payMonth: 'vel'
                },
                {
                    ID: 'omnis_111',
                    pid: 'perspiciatis',
                    empNames: 'et',
                    pay_type: 'nesciunt',
                    Amount: 'impedit',
                    ID_No: 'itaque',
                    PinNo: 'perspiciatis',
                    payMonth: 'nesciunt'
                },
                {
                    ID: 'esse_121',
                    pid: 'reiciendis',
                    empNames: 'et',
                    pay_type: 'eum',
                    Amount: 'odio',
                    ID_No: 'voluptatibus',
                    PinNo: 'mollitia',
                    payMonth: 'quia'
                },
                {
                    ID: 'nesciunt_131',
                    pid: 'ut',
                    empNames: 'consequatur',
                    pay_type: 'nostrum',
                    Amount: 'ad',
                    ID_No: 'veniam',
                    PinNo: 'odit',
                    payMonth: 'aliquam'
                },
                {
                    ID: 'quod_141',
                    pid: 'architecto',
                    empNames: 'aut',
                    pay_type: 'impedit',
                    Amount: 'quidem',
                    ID_No: 'in',
                    PinNo: 'culpa',
                    payMonth: 'sequi'
                },
                {
                    ID: 'autem_151',
                    pid: 'consectetur',
                    empNames: 'sit',
                    pay_type: 'et',
                    Amount: 'sapiente',
                    ID_No: 'magni',
                    PinNo: 'molestias',
                    payMonth: 'expedita'
                },
                {
                    ID: 'omnis_161',
                    pid: 'velit',
                    empNames: 'aliquid',
                    pay_type: 'laborum',
                    Amount: 'aut',
                    ID_No: 'quo',
                    PinNo: 'accusamus',
                    payMonth: 'et'
                },
                {
                    ID: 'accusantium_171',
                    pid: 'explicabo',
                    empNames: 'atque',
                    pay_type: 'est',
                    Amount: 'et',
                    ID_No: 'debitis',
                    PinNo: 'ut',
                    payMonth: 'provident'
                },
                {
                    ID: 'commodi_181',
                    pid: 'eum',
                    empNames: 'eum',
                    pay_type: 'maxime',
                    Amount: 'et',
                    ID_No: 'earum',
                    PinNo: 'aut',
                    payMonth: 'voluptate'
                },
                {
                    ID: 'harum_191',
                    pid: 'veniam',
                    empNames: 'provident',
                    pay_type: 'quia',
                    Amount: 'mollitia',
                    ID_No: 'culpa',
                    PinNo: 'voluptatibus',
                    payMonth: 'facere'
                },
                {
                    ID: 'ut_201',
                    pid: 'quidem',
                    empNames: 'officiis',
                    pay_type: 'voluptatem',
                    Amount: 'omnis',
                    ID_No: 'ut',
                    PinNo: 'provident',
                    payMonth: 'consequatur'
                },
                {
                    ID: 'dolorem_211',
                    pid: 'consectetur',
                    empNames: 'architecto',
                    pay_type: 'enim',
                    Amount: 'sed',
                    ID_No: 'dolores',
                    PinNo: 'officiis',
                    payMonth: 'incidunt'
                },
                {
                    ID: 'rerum_221',
                    pid: 'sunt',
                    empNames: 'minus',
                    pay_type: 'itaque',
                    Amount: 'perferendis',
                    ID_No: 'quo',
                    PinNo: 'possimus',
                    payMonth: 'ut'
                },
                {
                    ID: 'commodi_231',
                    pid: 'omnis',
                    empNames: 'qui',
                    pay_type: 'totam',
                    Amount: 'accusantium',
                    ID_No: 'laudantium',
                    PinNo: 'dolorem',
                    payMonth: 'autem'
                },
                {
                    ID: 'numquam_241',
                    pid: 'omnis',
                    empNames: 'enim',
                    pay_type: 'repellat',
                    Amount: 'officiis',
                    ID_No: 'dolores',
                    PinNo: 'nihil',
                    payMonth: 'esse'
                },
                {
                    ID: 'minima_251',
                    pid: 'placeat',
                    empNames: 'dolor',
                    pay_type: 'commodi',
                    Amount: 'error',
                    ID_No: 'voluptatem',
                    PinNo: 'rerum',
                    payMonth: 'sit'
                },
                {
                    ID: 'velit_261',
                    pid: 'facilis',
                    empNames: 'non',
                    pay_type: 'non',
                    Amount: 'et',
                    ID_No: 'quod',
                    PinNo: 'modi',
                    payMonth: 'sit'
                },
                {
                    ID: 'inventore_271',
                    pid: 'quas',
                    empNames: 'nisi',
                    pay_type: 'ut',
                    Amount: 'perferendis',
                    ID_No: 'saepe',
                    PinNo: 'explicabo',
                    payMonth: 'vel'
                },
                {
                    ID: 'quia_281',
                    pid: 'iste',
                    empNames: 'consequatur',
                    pay_type: 'sequi',
                    Amount: 'laboriosam',
                    ID_No: 'odit',
                    PinNo: 'sunt',
                    payMonth: 'repellat'
                },
                {
                    ID: 'earum_291',
                    pid: 'beatae',
                    empNames: 'amet',
                    pay_type: 'doloremque',
                    Amount: 'est',
                    ID_No: 'vel',
                    PinNo: 'quaerat',
                    payMonth: 'error'
                }
            ],
            proxy: {
                type: 'memory'
            }
        },
        payeReturns: {
            model: 'PayrollApp.model.PayeReturns',
            proxy: {
                type: 'memory'
            }
        },
        payeReturns: {
            model: 'PayrollApp.model.PayeReturns',
            proxy: {
                type: 'memory'
            }
        }
    }

});