/*
 * File: app/view/PayeReturns.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayeReturns', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.payereturns',

    requires: [
        'PayrollApp.view.PayeReturnsViewModel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'payereturns'
    },
    height: 577,
    width: 885,
    columnLines: true,
    store: 'PayeReturnsStore',

    dockedItems: [
        {
            xtype: 'pagingtoolbar',
            dock: 'bottom',
            width: 360,
            displayInfo: true,
            store: 'NhifReturnsStore'
        },
        {
            xtype: 'container',
            dock: 'top',
            height: 40,
            width: 100,
            layout: 'absolute',
            items: [
                {
                    xtype: 'combobox',
                    x: -2,
                    y: 5,
                    itemId: 'payeeMonth',
                    width: 294,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    displayField: 'Month',
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'button',
                    x: 515,
                    y: 5,
                    height: 31,
                    width: 164,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 685,
                    y: 5,
                    height: 30,
                    itemId: 'cmdExportPaye',
                    width: 135,
                    text: '<b>Export</b>'
                }
            ]
        }
    ],
    columns: [
        {
            xtype: 'gridcolumn',
            width: 64,
            dataIndex: 'ID',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            width: 58,
            dataIndex: 'pid',
            text: 'Pid'
        },
        {
            xtype: 'gridcolumn',
            width: 169,
            dataIndex: 'empNames',
            text: 'Emp Names'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'pay_type',
            text: 'Pay Type'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'Amount',
            text: 'Amount'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'ID_No',
            text: 'Id No'
        },
        {
            xtype: 'gridcolumn',
            width: 152,
            dataIndex: 'PinNo',
            text: 'Pin No'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'payMonth',
            text: 'Pay Month'
        }
    ]

});