/*
 * File: app/view/PayrollPostingWindow.js
 * Date: Fri Aug 28 2015 06:32:23 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollPostingWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.payrollpostingwindow',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    frame: true,
    height: 273,
    width: 384,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 15,
                    itemId: 'payMonth',
                    width: 305,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    displayField: 'month',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 105,
                    itemId: 'PaymentType',
                    width: 305,
                    fieldLabel: 'Pay Type',
                    labelAlign: 'right',
                    displayField: 'PayType',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayTypeStore',
                    typeAhead: true,
                    valueField: 'PayType'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 75,
                    itemId: 'CatID',
                    width: 305,
                    fieldLabel: 'Pay Category',
                    labelAlign: 'right',
                    allowBlank: false,
                    displayField: 'CatName',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayCategoryStore',
                    typeAhead: true,
                    valueField: 'CatName'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 45,
                    itemId: 'empBranch',
                    width: 305,
                    fieldLabel: 'Employee Branch',
                    labelAlign: 'right',
                    displayField: 'BranchName',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayBranchStore',
                    typeAhead: true,
                    valueField: 'BranchName'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 135,
                    itemId: 'pid1',
                    fieldLabel: 'From Pid',
                    labelAlign: 'right'
                },
                {
                    xtype: 'textfield',
                    x: 20,
                    y: 165,
                    itemId: 'pid2',
                    fieldLabel: 'To Pid',
                    labelAlign: 'right'
                },
                {
                    xtype: 'button',
                    x: 5,
                    y: 210,
                    height: 35,
                    itemId: 'cmdPreviewPostings',
                    width: 110,
                    text: '<b>Preview</b>'
                },
                {
                    xtype: 'button',
                    x: 125,
                    y: 210,
                    height: 35,
                    itemId: 'cmdPrintPostings',
                    width: 110,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 255,
                    y: 210,
                    height: 35,
                    itemId: 'cmdClose',
                    width: 105,
                    text: '<b>Close</b>'
                }
            ]
        });

        me.callParent(arguments);
    }

});