/*
 * File: app/view/PayRatesForm.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayRatesForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.payratesform',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    draggable: true,
    frame: true,
    height: 565,
    padding: 0,
    width: 824,
    layout: 'absolute',
    bodyPadding: 0,
    header: false,
    simpleDrag: true,
    url: 'data/updateFunctions.php?task=updateItems',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'data/updateFunctions.php?task=updateItems'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 5,
                    y: 175,
                    height: 390,
                    itemId: 'payRatesGrid',
                    width: 815,
                    title: 'Payment Rates',
                    store: 'PayRatesStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'PayRatesStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'RateName',
                            text: 'RateName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Value',
                            text: 'Value'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Lower_Limit',
                            text: 'Lower_Limit'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Upper_Limit',
                            text: 'Upper_Limit'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Rate',
                            text: 'Rate'
                        },
                        {
                            xtype: 'actioncolumn',
                            Text: 'Delete',
                            id: 'deleteRates',
                            width: 61,
                            align: 'center',
                            text: 'Delete',
                            altText: 'Delete',
                            items: [
                                {
                                    altText: 'Delete',
                                    icon: 'icons/delete1.jpg',
                                    tooltip: 'Delete Rate'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 35,
                    width: 345,
                    fieldLabel: 'Rate Name',
                    labelAlign: 'right',
                    name: 'RateName',
                    tabIndex: 1
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 5,
                    width: 155,
                    fieldLabel: 'ID',
                    labelAlign: 'right',
                    name: 'ID',
                    readOnly: true,
                    tabIndex: 1
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 60,
                    fieldLabel: 'Value',
                    labelAlign: 'right',
                    name: 'Value',
                    tabIndex: 2
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 85,
                    fieldLabel: 'Lower Limit',
                    labelAlign: 'right',
                    name: 'Lower_Limit',
                    tabIndex: 3
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 110,
                    fieldLabel: 'Upper Limit',
                    labelAlign: 'right',
                    name: 'Upper_Limit',
                    tabIndex: 4
                },
                {
                    xtype: 'textfield',
                    x: 25,
                    y: 135,
                    fieldLabel: 'Rate',
                    labelAlign: 'right',
                    name: 'Rate',
                    tabIndex: 5
                },
                {
                    xtype: 'button',
                    x: 375,
                    y: 120,
                    height: 35,
                    itemId: 'cmdNew',
                    width: 105,
                    tabIndex: 7,
                    text: '<b>New</b>'
                },
                {
                    xtype: 'button',
                    x: 505,
                    y: 120,
                    height: 35,
                    itemId: 'cmdSaveRates',
                    width: 105,
                    tabIndex: 6,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 665,
                    y: 120,
                    height: 35,
                    itemId: 'cmdClose',
                    width: 105,
                    tabIndex: 8,
                    text: '<b>Close</b>'
                },
                {
                    xtype: 'textfield',
                    x: 655,
                    y: 30,
                    width: 120,
                    name: 'formStatus',
                    readOnly: true
                }
            ]
        });

        me.callParent(arguments);
    }

});