/*
 * File: app/view/PayRatesForm.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayRatesForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.payratesform',

    requires: [
        'PayrollApp.view.PayRatesFormViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'payratesform'
    },
    draggable: true,
    frame: true,
    height: 565,
    padding: 0,
    width: 824,
    layout: 'absolute',
    bodyPadding: 0,
    header: false,
    simpleDrag: true,
    url: 'data/updateFunctions.php?task=updateItems',

    items: [
        {
            xtype: 'gridpanel',
            x: 0,
            y: 215,
            height: 390,
            itemId: 'payRatesGrid',
            width: 815,
            title: 'Payment Rates',
            store: 'PayRatesStore',
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PayRatesStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'RateName',
                    text: 'RateName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Value',
                    text: 'Value'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Lower_Limit',
                    text: 'Lower_Limit'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Upper_Limit',
                    text: 'Upper_Limit'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Rate',
                    text: 'Rate'
                },
                {
                    xtype: 'actioncolumn',
                    Text: 'Delete',
                    id: 'deleteRates',
                    width: 61,
                    align: 'center',
                    text: 'Delete',
                    altText: 'Delete',
                    items: [
                        {
                            altText: 'Delete',
                            icon: 'icons/delete1.jpg',
                            tooltip: 'Delete Rate'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 40,
            tabIndex: 1,
            width: 345,
            fieldLabel: 'Rate Name',
            labelAlign: 'right',
            name: 'RateName'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 5,
            tabIndex: 1,
            width: 155,
            fieldLabel: 'ID',
            labelAlign: 'right',
            name: 'ID',
            readOnly: true
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 75,
            tabIndex: 2,
            fieldLabel: 'Value',
            labelAlign: 'right',
            name: 'Value'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 110,
            tabIndex: 3,
            fieldLabel: 'Lower Limit',
            labelAlign: 'right',
            name: 'Lower_Limit'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 145,
            tabIndex: 4,
            fieldLabel: 'Upper Limit',
            labelAlign: 'right',
            name: 'Upper_Limit'
        },
        {
            xtype: 'textfield',
            x: 25,
            y: 180,
            tabIndex: 5,
            fieldLabel: 'Rate',
            labelAlign: 'right',
            name: 'Rate'
        },
        {
            xtype: 'button',
            x: 405,
            y: 170,
            height: 35,
            itemId: 'cmdNew',
            tabIndex: 7,
            width: 105,
            text: '<b>New</b>'
        },
        {
            xtype: 'button',
            x: 545,
            y: 170,
            height: 35,
            itemId: 'cmdSaveRates',
            tabIndex: 6,
            width: 105,
            text: '<b>Save</b>'
        },
        {
            xtype: 'button',
            x: 675,
            y: 170,
            height: 35,
            itemId: 'cmdClose',
            tabIndex: 8,
            width: 105,
            text: '<b>Close</b>'
        },
        {
            xtype: 'textfield',
            x: 655,
            y: 30,
            width: 120,
            name: 'formStatus',
            readOnly: true
        }
    ]

});