/*
 * File: app/view/PayrollMainViewController.js
 * Date: Fri Aug 25 2023 11:28:02 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollMainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.payrollmain',

    onPanelAfterRender: function(component, eOpts) {
        var period=sessionStorage.getItem("Period");
        var userName=sessionStorage.getItem("User");

        component.down('#Period').setValue(period);
        component.down('#userName').setValue(userName);
    }

});
