/*
 * File: app/view/PayrollPostingWindow.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollPostingWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.payrollpostingwindow',

    requires: [
        'PayrollApp.view.PayrollPostingWindowViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'payrollpostingwindow'
    },
    frame: true,
    height: 239,
    width: 433,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 20,
            y: 40,
            itemId: 'payMonth',
            tabIndex: 3,
            width: 220,
            fieldLabel: 'Payroll Month',
            labelAlign: 'right',
            displayField: 'Month',
            minChars: 2,
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 145,
            itemId: 'PaymentType',
            tabIndex: 6,
            width: 380,
            fieldLabel: 'Pay Type',
            labelAlign: 'right',
            displayField: 'PayType',
            minChars: 2,
            queryMode: 'local',
            store: 'PayTypeStore',
            typeAhead: true,
            valueField: 'PayType'
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 110,
            itemId: 'CatID',
            tabIndex: 5,
            width: 380,
            fieldLabel: 'Pay Category',
            labelAlign: 'right',
            allowBlank: false,
            displayField: 'CatName',
            minChars: 2,
            queryMode: 'local',
            store: 'PayCategoryStore',
            typeAhead: true,
            valueField: 'CatName'
        },
        {
            xtype: 'combobox',
            x: 0,
            y: 75,
            itemId: 'empBranch',
            tabIndex: 4,
            width: 400,
            fieldLabel: 'Employee Branch',
            labelAlign: 'right',
            labelWidth: 120,
            displayField: 'BranchName',
            minChars: 2,
            queryMode: 'local',
            store: 'PayBranchStore',
            typeAhead: true,
            valueField: 'BranchName'
        },
        {
            xtype: 'textfield',
            x: 20,
            y: 5,
            itemId: 'pid1',
            tabIndex: 1,
            width: 220,
            fieldLabel: 'From Pid',
            labelAlign: 'right'
        },
        {
            xtype: 'textfield',
            x: 235,
            y: 5,
            itemId: 'pid2',
            tabIndex: 2,
            width: 165,
            fieldLabel: 'To Pid',
            labelAlign: 'right',
            labelWidth: 60
        },
        {
            xtype: 'button',
            x: 15,
            y: 190,
            height: 35,
            itemId: 'cmdPreviewPostings',
            width: 110,
            text: '<b>Preview</b>'
        },
        {
            xtype: 'button',
            x: 155,
            y: 190,
            height: 35,
            itemId: 'cmdPrintPostings',
            width: 110,
            text: '<b>Print</b>'
        },
        {
            xtype: 'button',
            x: 310,
            y: 190,
            height: 35,
            itemId: 'cmdClose',
            width: 105,
            text: '<b>Close</b>'
        }
    ]

});