/*
 * File: app/view/PayrollMain.js
 * Date: Fri Aug 25 2023 12:48:12 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollMain', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.payrollmain',

    requires: [
        'PayrollApp.view.PayrollMainViewModel',
        'PayrollApp.view.PayrollMainViewController',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Panel',
        'Ext.Img',
        'Ext.form.field.Display',
        'Ext.button.Button'
    ],

    controller: 'payrollmain',
    viewModel: {
        type: 'payrollmain'
    },
    itemId: 'mnuP9Report',
    scrollable: true,
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            scrollable: true,
            width: 239,
            layout: 'accordion',
            animCollapse: true,
            collapsible: true,
            title: 'Payroll Menu',
            items: [
                {
                    xtype: 'menu',
                    floating: false,
                    width: 227,
                    animCollapse: true,
                    collapsed: false,
                    collapsible: true,
                    title: 'Main Menu',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuEmpRegister',
                            icon: 'icons/register.png',
                            text: 'Employee Register',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuEmployeePayments',
                            icon: 'icons/note_accept.png',
                            text: 'Employee Payments',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            id: 'mnuProcessPayroll',
                            icon: 'icons/Application-ok.png',
                            iconCls: '',
                            text: 'Process Payroll',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            id: 'mnuPostPayroll',
                            icon: 'icons/Application-run.png',
                            text: 'Post Payroll',
                            focusable: true
                        }
                    ]
                },
                {
                    xtype: 'menu',
                    floating: false,
                    width: 227,
                    animCollapse: true,
                    collapsed: false,
                    collapsible: true,
                    title: 'Administration',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuCompanySettings',
                            icon: 'icons/compile.png',
                            iconCls: '',
                            text: 'Company Settings',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBranches',
                            icon: 'icons/Application-add.png',
                            text: 'Branches',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuDepartments',
                            icon: 'icons/news.png',
                            text: 'Departments',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuPayTypes',
                            icon: 'icons/compile-add.png',
                            text: 'Paytypes',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuPayRates',
                            icon: 'icons/news-edit.png',
                            text: 'Rates',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBanks',
                            icon: 'icons/date.png',
                            text: 'Banks',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBankBranches',
                            icon: 'icons/date-del.png',
                            text: 'Bank Branches',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuJobTitles',
                            icon: 'icons/note.png',
                            text: 'Job Titles',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuJobGroups',
                            icon: 'icons/link.png',
                            text: 'Job Groups',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuLoanTypes',
                            icon: 'icons/tag-blue.png',
                            text: 'Loan Types',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuLeaves',
                            icon: 'icons/image-edit.png',
                            text: 'Leaves',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuOvertime',
                            icon: 'icons/time-edit.png',
                            text: 'Overtime',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBatchUpdate',
                            icon: 'icons/user-edit.png',
                            text: 'Batch Update',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuUsers1',
                            icon: 'icons/user-edit.png',
                            text: 'Users Administration',
                            focusable: true
                        }
                    ]
                },
                {
                    xtype: 'menu',
                    floating: false,
                    width: 227,
                    animCollapse: true,
                    collapsed: false,
                    collapsible: true,
                    title: 'Reports',
                    items: [
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuPayslips',
                            icon: 'icons/news-ok.png',
                            text: 'Payslips',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuOpenPostingWindow',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Payroll Postings',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuPayrollListing',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Payroll Listings',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuTrialBalance',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Trial Balance',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuP9Report',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'P9A Report',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuP9AReport',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'P9A Hosp Report',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuNssfReturns',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'NSSF Returns',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuNhifReturns',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'NHIF Returns',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuPayeReturns',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'PAYE Returns',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuEarnings',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Monthly Earnings',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuDeductions',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Monthly Deductions',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBankPayments',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Bank Payment Schedule',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuDepartmentTotals',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Monthly Department Totals',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Monthly Organisation Totals',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuBankLoans',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Bank Loan Deductions',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuCooperativeContributions',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Cooperative/Other Deductions',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Employees List',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuSaccoReports',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Sacco Reports',
                            focusable: true
                        },
                        {
                            xtype: 'menuitem',
                            itemId: 'mnuWelfareReports',
                            icon: 'icons/Chart2-Edit.png',
                            text: 'Welfare Reports',
                            focusable: true
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'form',
            region: 'center',
            scrollable: true,
            layout: 'fit'
        },
        {
            xtype: 'panel',
            region: 'north',
            height: 46,
            bodyBorder: true,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'image',
                    height: 45,
                    width: 60,
                    src: 'images/chmis.png'
                },
                {
                    xtype: 'displayfield',
                    itemId: 'CompanyName',
                    width: 446,
                    name: '',
                    value: 'JAMII TEKELEZI PAYROLL',
                    fieldStyle: 'font-size: large;font-weight: bold;color: green;'
                }
            ],
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'right',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            itemId: 'Period',
                            width: 205,
                            fieldLabel: 'Period',
                            labelAlign: 'right',
                            labelStyle: 'font-size: 14px;font-weight: bold;color: green;',
                            labelWidth: 80,
                            fieldStyle: 'font-size: 14px;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'displayfield',
                            itemId: 'userName',
                            width: 205,
                            fieldLabel: 'Logged User',
                            labelStyle: 'font-size: 14px;font-weight: bold;color: green;',
                            labelWidth: 150,
                            fieldStyle: 'font-size: 14px;font-weight: bold;color: green;'
                        },
                        {
                            xtype: 'button',
                            flex: 0,
                            itemId: 'cmdlogout',
                            width: 129,
                            text: '<b>Logout</b>'
                        }
                    ]
                }
            ],
            listeners: {
                afterrender: 'onPanelAfterRender'
            }
        }
    ]

});