/*
 * File: app/view/PayrollListingWindow.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollListingWindow', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.payrolllistingwindow',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    frame: true,
    height: 216,
    width: 394,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 20,
                    itemId: 'payMonth',
                    width: 320,
                    fieldLabel: 'Payroll Month',
                    labelAlign: 'right',
                    displayField: 'month',
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 50,
                    itemId: 'empBranch',
                    width: 320,
                    fieldLabel: 'Branch',
                    labelAlign: 'right',
                    displayField: 'BranchName',
                    store: 'PayBranchStore',
                    valueField: 'BranchName'
                },
                {
                    xtype: 'button',
                    x: 20,
                    y: 100,
                    height: 40,
                    itemId: 'cmdPreviewListing',
                    width: 110,
                    text: '<b>Preview Report'
                },
                {
                    xtype: 'button',
                    x: 155,
                    y: 100,
                    height: 40,
                    itemId: 'cmdPrintTrialbalance',
                    width: 110,
                    text: '<b>Print Report'
                },
                {
                    xtype: 'button',
                    x: 275,
                    y: 100,
                    height: 40,
                    itemId: 'cmdExportListing',
                    width: 110,
                    text: '<b>Export Report'
                },
                {
                    xtype: 'button',
                    x: 235,
                    y: 155,
                    height: 40,
                    itemId: 'cmdClose',
                    width: 150,
                    text: '<b>Close'
                }
            ]
        });

        me.callParent(arguments);
    }

});