/*
 * File: app/view/PayrollBranches.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayrollBranches', {
    extend: 'Ext.form.Panel',
    alias: 'widget.payrollbranches',

    requires: [
        'PayrollApp.view.PayrollBranchesViewModel',
        'Ext.form.field.Text',
        'Ext.XTemplate',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'payrollbranches'
    },
    frame: true,
    height: 438,
    width: 801,
    layout: 'absolute',
    url: 'data/updateFunctions.php?task=updateItems',

    items: [
        {
            xtype: 'textfield',
            x: -2,
            y: 45,
            itemId: 'DeptName',
            tabIndex: 1,
            width: 350,
            afterLabelTextTpl: [
                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
            ],
            fieldLabel: 'Branch Name',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'BranchName',
            allowBlank: false
        },
        {
            xtype: 'textfield',
            x: -4,
            y: 10,
            itemId: 'DeptName1',
            width: 190,
            fieldLabel: 'ID',
            labelAlign: 'right',
            labelWidth: 120,
            name: 'ID'
        },
        {
            xtype: 'gridpanel',
            x: 0,
            y: 95,
            height: 335,
            itemId: 'branchesGrid',
            width: 800,
            title: 'Branch List',
            store: 'PayBranchStore',
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PayBranchStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 202,
                    dataIndex: 'BranchName',
                    text: 'BranchName'
                },
                {
                    xtype: 'actioncolumn',
                    id: 'deleteBranch',
                    align: 'center',
                    text: 'Delete',
                    items: [
                        {
                            icon: 'icons/delete1.jpg'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            x: 535,
            y: 55,
            height: 35,
            itemId: 'cmdNew',
            width: 101,
            text: '<b>New</b>'
        },
        {
            xtype: 'button',
            x: 415,
            y: 55,
            height: 35,
            itemId: 'cmdSaveBranches',
            tabIndex: 2,
            width: 101,
            text: '<b>Save</b>'
        },
        {
            xtype: 'button',
            x: 650,
            y: 55,
            height: 35,
            itemId: 'cmdClose',
            width: 101,
            text: '<b>Close</b>'
        },
        {
            xtype: 'textfield',
            x: 570,
            y: 5,
            name: 'formStatus',
            readOnly: true
        }
    ]

});