/*
 * File: app/view/PayslipsWin.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayslipsWin', {
    extend: 'Ext.form.Panel',
    alias: 'widget.payslipswin',

    requires: [
        'PayrollApp.view.PayslipsWinViewModel',
        'Ext.form.field.ComboBox',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio',
        'Ext.button.Button',
        'Ext.XTemplate'
    ],

    config: {
        styleHtmlCls: 'styleHtmlCls'
    },

    viewModel: {
        type: 'payslipswin'
    },
    frame: true,
    height: 309,
    tpl: [
        'Test'
    ],
    width: 407,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 20,
            y: 5,
            itemId: 'payslipMonth',
            width: 270,
            fieldLabel: 'Payroll Month',
            labelAlign: 'right',
            displayField: 'Month',
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'radiogroup',
            x: 15,
            y: 175,
            height: 80,
            width: 285,
            layout: 'absolute',
            fieldLabel: 'Payslips Per Page',
            items: [
                {
                    xtype: 'radiofield',
                    x: 0,
                    y: -2,
                    itemId: 'pages1',
                    name: 'pages',
                    boxLabel: '1',
                    inputValue: '1'
                },
                {
                    xtype: 'radiofield',
                    x: 0,
                    y: 25,
                    itemId: 'pages2',
                    name: 'pages',
                    boxLabel: '2',
                    inputValue: '2'
                },
                {
                    xtype: 'radiofield',
                    x: -1,
                    y: 50,
                    itemId: 'pages3',
                    name: 'pages',
                    boxLabel: '3',
                    inputValue: '3'
                }
            ]
        },
        {
            xtype: 'textfield',
            x: 20,
            y: 110,
            itemId: 'pid1',
            width: 190,
            fieldLabel: 'Between PID',
            labelAlign: 'right',
            name: 'pid1'
        },
        {
            xtype: 'textfield',
            x: 20,
            y: 145,
            itemId: 'pid2',
            width: 190,
            fieldLabel: 'And PID',
            labelAlign: 'right',
            name: 'pid2'
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 40,
            itemId: 'empBranch',
            width: 270,
            fieldLabel: 'Branch',
            labelAlign: 'right',
            name: 'EmpBranch',
            emptyText: 'Select Branch',
            displayField: 'BranchName',
            queryMode: 'local',
            store: 'PayBranchStore',
            typeAhead: true,
            valueField: 'BranchName'
        },
        {
            xtype: 'combobox',
            x: 20,
            y: 75,
            itemId: 'department',
            width: 270,
            fieldLabel: 'Department',
            labelAlign: 'right',
            name: 'Department',
            emptyText: 'Select Department',
            displayField: 'deptName',
            queryMode: 'local',
            store: 'PayDeptStore',
            typeAhead: true,
            valueField: 'deptName'
        },
        {
            xtype: 'button',
            x: 15,
            y: 265,
            height: 35,
            hidden: true,
            itemId: 'cmdSlipPreview',
            width: 120,
            text: '<b>Preview Payslip</b>'
        },
        {
            xtype: 'button',
            x: 10,
            y: 260,
            height: 35,
            itemId: 'cmdEmailPayslip',
            width: 125,
            iconCls: 'x-fa fa-inbox',
            text: '<b>Email Payslip</b>'
        },
        {
            xtype: 'button',
            x: 145,
            y: 260,
            height: 35,
            itemId: 'cmdPrintPayslip',
            width: 130,
            iconCls: 'x-fa fa-print',
            text: '<b>Print Payslip</b>'
        },
        {
            xtype: 'button',
            x: 285,
            y: 260,
            height: 35,
            itemId: 'cmdClose',
            width: 110,
            iconCls: 'x-fa fa-close',
            text: '<b>Cancel</b>'
        }
    ]

});