/*
 * File: app/view/PayTypesForm.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PayTypesForm', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.paytypesform',

    requires: [
        'PayrollApp.view.PayTypesFormViewModel',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Action'
    ],

    viewModel: {
        type: 'paytypesform'
    },
    height: 616,
    width: 835,
    header: false,

    items: [
        {
            xtype: 'form',
            frame: true,
            height: 274,
            itemId: 'paytypesfrm',
            layout: 'absolute',
            bodyPadding: 10,
            url: 'data/updateFunctions.php?task=updateItems',
            items: [
                {
                    xtype: 'combobox',
                    x: 15,
                    y: 5,
                    tabIndex: 1,
                    fieldLabel: 'Pay Category',
                    name: 'CatID',
                    displayField: 'CatName',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayCategoryStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'textfield',
                    x: 15,
                    y: 75,
                    tabIndex: 3,
                    width: 295,
                    fieldLabel: 'Pay Type',
                    labelAlign: 'right',
                    name: 'PayType'
                },
                {
                    xtype: 'textfield',
                    x: 15,
                    y: 40,
                    tabIndex: 2,
                    width: 170,
                    fieldLabel: 'Type ID',
                    labelAlign: 'right',
                    name: 'ID'
                },
                {
                    xtype: 'textfield',
                    x: 480,
                    y: 150,
                    tabIndex: 12,
                    width: 295,
                    fieldLabel: 'Interest Name',
                    labelAlign: 'right',
                    name: 'InterestName'
                },
                {
                    xtype: 'textfield',
                    x: 665,
                    y: 185,
                    tabIndex: 12,
                    width: 110,
                    labelAlign: 'right',
                    name: 'formStatus',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    x: 480,
                    y: 115,
                    tabIndex: 11,
                    width: 295,
                    fieldLabel: 'Interest Code',
                    labelAlign: 'right',
                    name: 'InterestCode'
                },
                {
                    xtype: 'textfield',
                    x: 460,
                    y: 10,
                    tabIndex: 8,
                    width: 295,
                    fieldLabel: 'GL Account Code',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'Gl_acc'
                },
                {
                    xtype: 'textfield',
                    x: 480,
                    y: 80,
                    tabIndex: 10,
                    width: 295,
                    fieldLabel: 'Interest',
                    labelAlign: 'right',
                    name: 'Interest'
                },
                {
                    xtype: 'textfield',
                    x: 460,
                    y: 45,
                    tabIndex: 9,
                    width: 295,
                    fieldLabel: 'GL Account Name',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'Gl_desc'
                },
                {
                    xtype: 'checkboxfield',
                    x: 15,
                    y: 100,
                    tabIndex: 4,
                    fieldLabel: 'Fixed',
                    labelAlign: 'right',
                    name: 'Fixed',
                    uncheckedValue: 'off'
                },
                {
                    xtype: 'checkboxfield',
                    x: 15,
                    y: 125,
                    tabIndex: 5,
                    fieldLabel: 'Contribution',
                    labelAlign: 'right',
                    name: 'Contribution',
                    uncheckedValue: 'off'
                },
                {
                    xtype: 'checkboxfield',
                    x: 15,
                    y: 150,
                    tabIndex: 6,
                    fieldLabel: 'Posted',
                    labelAlign: 'right',
                    name: 'Posted',
                    uncheckedValue: 'off'
                },
                {
                    xtype: 'textareafield',
                    x: 15,
                    y: 180,
                    height: 82,
                    tabIndex: 7,
                    width: 400,
                    fieldLabel: 'Notes',
                    labelAlign: 'right',
                    name: 'Notes'
                },
                {
                    xtype: 'button',
                    x: 600,
                    y: 230,
                    height: 35,
                    itemId: 'cmdNew',
                    tabIndex: 14,
                    width: 105,
                    text: '<b>New</b>'
                },
                {
                    xtype: 'button',
                    x: 470,
                    y: 230,
                    height: 35,
                    itemId: 'cmdSavePaytypes',
                    tabIndex: 13,
                    width: 100,
                    text: '<b>Save</b>'
                },
                {
                    xtype: 'button',
                    x: 720,
                    y: 230,
                    height: 35,
                    itemId: 'cmdClose',
                    tabIndex: 15,
                    width: 105,
                    text: '<b>Close</b>'
                },
                {
                    xtype: 'textfield',
                    x: 220,
                    y: 95,
                    hidden: true,
                    name: 'formStatus'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            height: 357,
            itemId: 'paytypesgrid',
            title: 'Pay Types List',
            store: 'PayTypeStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 36,
                    dataIndex: 'ID',
                    locked: true,
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 53,
                    dataIndex: 'CatID',
                    locked: true,
                    text: 'CatID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 168,
                    dataIndex: 'PayType',
                    locked: true,
                    text: 'PayType'
                },
                {
                    xtype: 'checkcolumn',
                    width: 53,
                    dataIndex: 'Fixed',
                    text: 'Fixed'
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'Contribution',
                    text: 'Contribution'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'gl_acc',
                    text: 'Gl_acc'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'gl_desc',
                    text: 'Gl_desc'
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'Posted',
                    text: 'Posted'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Interest',
                    text: 'Interest'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'InterestCode',
                    text: 'InterestCode'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'InterestName',
                    text: 'InterestName'
                },
                {
                    xtype: 'checkcolumn',
                    dataIndex: 'Recurrent',
                    text: 'Recurrent'
                },
                {
                    xtype: 'actioncolumn',
                    id: 'deletePaytypes',
                    align: 'center',
                    text: 'Delete',
                    items: [
                        {
                            icon: 'icons/delete1.jpg'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PayTypeStore'
                }
            ]
        }
    ]

});