/*
 * File: app/view/PostPayroll.js
 * Date: Mon Apr 13 2015 09:30:55 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PostPayroll', {
    extend: 'Ext.form.Panel',
    alias: 'widget.postpayroll',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Display'
    ],

    frame: true,
    height: 693,
    layout: 'absolute',
    bodyPadding: 10,
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'PAYROLL POSTING',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 0,
                    height: 655,
                    itemId: 'empPostGridSummary',
                    width: 455,
                    title: 'Payroll Summary',
                    columnLines: true,
                    store: 'PaymentsSummaryStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'PaymentsSummaryStore'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 52,
                            dataIndex: 'PID',
                            text: 'PID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 199,
                            dataIndex: 'emp_names',
                            text: 'Emp_names'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'total',
                            text: 'Total'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'pstatus',
                            text: 'Pstatus'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    x: 460,
                    y: 95,
                    height: 560,
                    title: 'Employee Payments Details',
                    columnLines: true,
                    store: 'ProllPaymentsStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 55,
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 55,
                            dataIndex: 'PID',
                            text: 'PID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 73,
                            dataIndex: 'PayType',
                            text: 'PayType'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 142,
                            dataIndex: 'PayName',
                            text: 'PayName'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Amount',
                            text: 'Amount'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Balance',
                            text: 'Balance'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'ProllPaymentsStore'
                        }
                    ]
                },
                {
                    xtype: 'combobox',
                    x: 490,
                    y: 15,
                    itemId: 'postMonth',
                    width: 335,
                    fieldLabel: '<b>Select Payroll Month</b>',
                    labelWidth: 140,
                    forceSelection: true,
                    store: [
                        [
                            'January',
                            'January'
                        ],
                        [
                            'February',
                            'February'
                        ],
                        [
                            'March',
                            'March'
                        ],
                        [
                            'April',
                            'April'
                        ],
                        [
                            'May',
                            'May'
                        ],
                        [
                            'June',
                            'June'
                        ],
                        [
                            'July',
                            'July'
                        ],
                        [
                            'August',
                            'August'
                        ],
                        [
                            'September',
                            'September'
                        ],
                        [
                            'October',
                            'October'
                        ],
                        [
                            'November',
                            'November'
                        ],
                        [
                            'December',
                            'December'
                        ]
                    ]
                },
                {
                    xtype: 'button',
                    x: 635,
                    y: 50,
                    height: 40,
                    itemId: 'cmdPostPayroll',
                    width: 145,
                    text: '<b> POST PAYROLL</B>'
                },
                {
                    xtype: 'button',
                    x: 1075,
                    y: 50,
                    height: 40,
                    itemId: 'cmdClose',
                    width: 170,
                    text: '<b>CANCEL</b>'
                },
                {
                    xtype: 'button',
                    x: 790,
                    y: 50,
                    height: 40,
                    itemId: 'cmdPreviewPayslip',
                    width: 145,
                    text: '<b>Preview Payslip</b>'
                },
                {
                    xtype: 'displayfield',
                    x: 920,
                    y: 30,
                    itemId: 'payrollStatus',
                    width: 250,
                    name: 'payrollStatus',
                    fieldStyle: 'font-size: medium;font-weight: bold;color: red;'
                }
            ]
        });

        me.callParent(arguments);
    }

});