/*
 * File: app/view/PostByCode.js
 * Date: Sun Mar 08 2015 15:46:52 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PostByCode', {
    extend: 'Ext.form.Panel',
    alias: 'widget.postbycode',

    requires: [
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Column',
        'Ext.toolbar.Paging',
        'Ext.form.field.Text',
        'Ext.grid.plugin.CellEditing',
        'Ext.selection.CellModel',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Display'
    ],

    frame: true,
    height: 655,
    width: 952,
    layout: 'absolute',
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    x: 0,
                    y: 10,
                    height: 610,
                    itemId: 'payTypesGrid',
                    width: 290,
                    title: 'Pay Types',
                    store: 'PayTypeStore',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 47,
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'CatID',
                            text: 'CatID'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 201,
                            dataIndex: 'PayType',
                            text: 'PayType'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'Fixed',
                            text: 'Fixed'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'Contribution',
                            text: 'Contribution'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'gl_acc',
                            text: 'Gl_acc'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'gl_desc',
                            text: 'Gl_desc'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'Posted',
                            text: 'Posted'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'Interest',
                            text: 'Interest'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'InterestCode',
                            text: 'InterestCode'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'InterestName',
                            text: 'InterestName'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'Recurrent',
                            text: 'Recurrent'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'PayTypeStore'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    x: 290,
                    y: 70,
                    height: 550,
                    itemId: 'postByCodeGrid',
                    width: 650,
                    title: 'Payments',
                    columnLines: true,
                    store: 'BlankPaymentsStore',
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'BlankPaymentsStore'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    height: 33,
                                    itemId: 'cmdSavePaymentsPosting',
                                    width: 127,
                                    text: '<b>Save </b>'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 54,
                            dataIndex: 'Pid',
                            locked: true,
                            text: 'Pid'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 189,
                            dataIndex: 'EmpNames',
                            locked: true,
                            text: 'Names'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Amount',
                            text: 'Amount',
                            editor: {
                                xtype: 'textfield',
                                width: 100,
                                name: 'txtAmount',
                                enableKeyEvents: true,
                                selectOnFocus: true
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Balance',
                            text: 'Balance',
                            editor: {
                                xtype: 'textfield',
                                name: 'txtBalance'
                            }
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.CellEditing', {
                            clicksToEdit: 1
                        })
                    ],
                    selModel: Ext.create('Ext.selection.CellModel', {
                        mode: 'SINGLE'
                    })
                },
                {
                    xtype: 'fieldset',
                    x: 300,
                    y: 10,
                    height: 60,
                    width: 640,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'displayfield',
                            x: 0,
                            y: 15,
                            itemId: 'payTitle',
                            width: 500,
                            fieldLabel: 'Selected Pay Type',
                            labelStyle: 'font-size: small;font-weight: bold;color: green;',
                            labelWidth: 130,
                            fieldStyle: 'font-size: small;font-weight: bold;color: blue;'
                        },
                        {
                            xtype: 'textfield',
                            x: 455,
                            y: 20,
                            hidden: true,
                            itemId: 'txtPayTypeID',
                            width: 65
                        },
                        {
                            xtype: 'textfield',
                            x: 530,
                            y: 20,
                            hidden: true,
                            itemId: 'txtPayCatId',
                            width: 65
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});