/*
 * File: app/view/PostPayroll.js
 * Date: Fri Aug 25 2023 12:43:47 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.PostPayroll', {
    extend: 'Ext.form.Panel',
    alias: 'widget.postpayroll',

    requires: [
        'PayrollApp.view.PostPayrollViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Paging',
        'Ext.grid.column.Column',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'postpayroll'
    },
    frame: true,
    animCollapse: true,
    bodyPadding: 10,
    closable: true,
    collapsible: true,
    title: 'PAYROLL POSTING',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'gridpanel',
            flex: 0,
            itemId: 'empPostGridSummary',
            width: 466,
            bodyBorder: true,
            columnLines: true,
            store: 'PaymentsSummaryStore',
            viewConfig: {
                border: 1
            },
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PaymentsSummaryStore'
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 52,
                    dataIndex: 'PID',
                    text: 'PID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 199,
                    dataIndex: 'emp_names',
                    text: 'Emp_names'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'total',
                    text: 'Total'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'pstatus',
                    text: 'Pstatus'
                }
            ]
        },
        {
            xtype: 'gridpanel',
            flex: 1,
            title: 'Employee Payments Details',
            columnLines: true,
            store: 'ProllPaymentsStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 55,
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 55,
                    dataIndex: 'PID',
                    text: 'PID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 73,
                    dataIndex: 'PayType',
                    text: 'PayType'
                },
                {
                    xtype: 'gridcolumn',
                    width: 142,
                    dataIndex: 'PayName',
                    text: 'PayName'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Amount',
                    text: 'Amount'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Balance',
                    text: 'Balance'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'ProllPaymentsStore'
                },
                {
                    xtype: 'displayfield',
                    dock: 'top',
                    itemId: 'payrollStatus',
                    width: 100,
                    name: 'payrollStatus',
                    value: 'Payroll Status',
                    fieldStyle: 'font-size: medium;font-weight: bold;color: red;'
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    width: 100
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 44,
                    width: 100,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            itemId: 'postMonth',
                            width: 575,
                            fieldLabel: '<b>Select Payroll Month</b>',
                            labelWidth: 140,
                            displayField: 'Month',
                            forceSelection: true,
                            minChars: 3,
                            queryMode: 'local',
                            store: 'PayMonthsStore',
                            typeAhead: true,
                            valueField: 'ID'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'cmdPostPayroll',
                            width: 145,
                            text: '<b> POST PAYROLL</B>'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'cmdClose',
                            width: 170,
                            text: '<b>CANCEL</b>'
                        },
                        {
                            xtype: 'button',
                            height: 40,
                            itemId: 'cmdPreviewPayslip',
                            width: 145,
                            text: '<b>Preview Payslip</b>'
                        }
                    ]
                }
            ]
        }
    ]

});