/*
 * File: app/view/ProcessPayroll.js
 * Date: Fri Jul 30 2021 14:07:15 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.ProcessPayroll', {
    extend: 'Ext.form.Panel',
    alias: 'widget.processpayroll',

    requires: [
        'PayrollApp.view.ProcessPayrollViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.toolbar.Paging',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Display',
        'Ext.form.field.Checkbox'
    ],

    viewModel: {
        type: 'processpayroll'
    },
    frame: true,
    height: 754,
    layout: 'absolute',
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'Process Payroll',

    items: [
        {
            xtype: 'gridpanel',
            x: 10,
            y: 130,
            height: 575,
            itemId: 'empPayGridSummary',
            width: 425,
            columnLines: true,
            store: 'PaymentsSummaryStore',
            columns: [
                {
                    xtype: 'numbercolumn',
                    width: 67,
                    dataIndex: 'PID',
                    text: 'PID',
                    format: '000'
                },
                {
                    xtype: 'gridcolumn',
                    width: 181,
                    dataIndex: 'emp_names',
                    text: 'Emp_names'
                },
                {
                    xtype: 'numbercolumn',
                    align: 'right',
                    dataIndex: 'total',
                    text: 'Total'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'pstatus',
                    text: 'Pstatus'
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'PaymentsSummaryStore'
                },
                {
                    xtype: 'container',
                    dock: 'top',
                    height: 34,
                    width: 100,
                    layout: 'absolute',
                    items: [
                        {
                            xtype: 'button',
                            x: 285,
                            y: 0,
                            width: 115,
                            text: '<b>Search</b>'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: -1,
                            width: 285,
                            emptyText: 'Search by PID or Names'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            x: 445,
            y: 130,
            height: 570,
            itemId: 'empPayGridDetail',
            width: 841,
            columnLines: true,
            store: 'ProllPaymentsStore',
            columns: [
                {
                    xtype: 'gridcolumn',
                    width: 41,
                    dataIndex: 'ID',
                    text: 'ID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 63,
                    dataIndex: 'PID',
                    text: 'PID'
                },
                {
                    xtype: 'gridcolumn',
                    width: 73,
                    dataIndex: 'PayType',
                    text: 'PayType'
                },
                {
                    xtype: 'gridcolumn',
                    width: 145,
                    dataIndex: 'PayName',
                    text: 'PayName'
                },
                {
                    xtype: 'gridcolumn',
                    align: 'right',
                    dataIndex: 'Amount',
                    text: 'Amount'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'Balance',
                    text: 'Balance'
                }
            ]
        },
        {
            xtype: 'fieldset',
            x: 10,
            y: -10,
            height: 140,
            padding: '0 0 0 ',
            width: 505,
            layout: 'absolute',
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    x: 5,
                    y: 15,
                    itemId: 'payMonth',
                    width: 503,
                    fieldLabel: 'Select Payroll Month',
                    labelWidth: 130,
                    name: 'payMonth',
                    emptyText: 'Select the Payroll Month',
                    matchFieldWidth: false,
                    displayField: 'Month',
                    forceSelection: true,
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'button',
                    x: 185,
                    y: 95,
                    height: 35,
                    itemId: 'cmdUpdateTaxes',
                    width: 120,
                    text: '<b>Process Payroll</b>'
                },
                {
                    xtype: 'button',
                    x: 5,
                    y: 95,
                    height: 35,
                    itemId: 'cmdImportPayments',
                    width: 175,
                    text: '<b>Import Posted Payments</b>'
                },
                {
                    xtype: 'button',
                    x: 310,
                    y: 95,
                    height: 35,
                    itemId: 'cmdClearImports',
                    width: 185,
                    text: '<b>Clear Imported Payments</b>'
                },
                {
                    xtype: 'displayfield',
                    x: 10,
                    y: 50,
                    itemId: 'PayrollStatus',
                    width: 485,
                    value: 'Payroll Status',
                    fieldStyle: 'font-size: large;font-weight: bold;color: maroon;'
                },
                {
                    xtype: 'textfield',
                    x: 5,
                    y: 65,
                    hidden: true,
                    itemId: 'prollStatus',
                    fieldStyle: 'font-size: large;font-weight: bold;color: green;'
                }
            ]
        },
        {
            xtype: 'fieldset',
            x: 520,
            y: 5,
            frame: false,
            height: 130,
            padding: '0 0 0 0',
            layout: 'absolute',
            items: [
                {
                    xtype: 'displayfield',
                    x: -20,
                    y: -1,
                    itemId: 'pid',
                    fieldLabel: 'PID',
                    labelAlign: 'right',
                    name: 'PID',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'displayfield',
                    x: -18,
                    y: 85,
                    fieldLabel: 'Job Group',
                    labelAlign: 'right',
                    name: 'JobGroup',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'displayfield',
                    x: -20,
                    y: 65,
                    fieldLabel: 'Job Title',
                    labelAlign: 'right',
                    name: 'JobTitle',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'displayfield',
                    x: -20,
                    y: 45,
                    fieldLabel: 'Departmant',
                    labelAlign: 'right',
                    name: 'Department',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'displayfield',
                    x: -20,
                    y: 25,
                    shadow: true,
                    fieldLabel: 'Names',
                    labelAlign: 'right',
                    name: 'FirstName',
                    fieldStyle: 'font-size: small;font-weight: bold;color: green;'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: -7.666666999999997,
                    name: 'Taxable',
                    readOnly: true,
                    boxLabel: 'Taxable'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: 95,
                    name: 'NHIF',
                    readOnly: true,
                    boxLabel: 'NHIF'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: 70,
                    name: 'NSSF',
                    readOnly: true,
                    boxLabel: 'NSSF'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: 50,
                    name: 'Housed',
                    readOnly: true,
                    boxLabel: 'Housed'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: 30,
                    name: 'Unionisable',
                    readOnly: true,
                    boxLabel: 'Unionisable'
                },
                {
                    xtype: 'checkboxfield',
                    x: 410,
                    y: 10,
                    name: 'Pensionable',
                    readOnly: true,
                    boxLabel: 'Pensionable'
                },
                {
                    xtype: 'button',
                    x: 550,
                    y: 5,
                    height: 35,
                    hidden: true,
                    width: 145,
                    text: 'Post By PID'
                },
                {
                    xtype: 'button',
                    x: 760,
                    y: 50,
                    height: 35,
                    hidden: true,
                    itemId: 'cmdPostByPid',
                    width: 145,
                    text: '<b>Post By PID</b>'
                },
                {
                    xtype: 'button',
                    x: 550,
                    y: 45,
                    height: 35,
                    hidden: true,
                    itemId: 'cmdPostByCode',
                    width: 145,
                    text: '<b>Post By Code</b>'
                }
            ]
        }
    ]

});