/*
 * File: app/view/RegisterForm.js
 * Date: Thu Jul 29 2021 12:17:30 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.RegisterForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.registerform',

    requires: [
        'PayrollApp.view.RegisterFormViewModel',
        'Ext.form.FieldSet',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Date',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.CheckboxGroup',
        'Ext.form.field.Checkbox'
    ],

    viewModel: {
        type: 'registerform'
    },
    frame: true,
    height: 551,
    width: 797,
    layout: 'absolute',
    animCollapse: false,
    collapsible: false,
    url: 'data/getDataFunctions.php?task=updateEmployee',

    items: [
        {
            xtype: 'fieldset',
            x: 10,
            y: -6,
            border: '0 0 0 0',
            height: 225,
            margin: '0 0 0 0',
            padding: '0 0 0 0',
            width: 450,
            layout: 'absolute',
            title: 'Employee Details',
            items: [
                {
                    xtype: 'textfield',
                    x: -11,
                    y: 0,
                    tabIndex: 1,
                    width: 175,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Payroll No',
                    labelAlign: 'right',
                    name: 'PID',
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    x: 205,
                    y: 35,
                    tabIndex: 3,
                    width: 125,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    labelAlign: 'right',
                    name: 'FirstName',
                    allowBlank: false,
                    emptyText: 'First Name'
                },
                {
                    xtype: 'textfield',
                    x: -12,
                    y: 35,
                    tabIndex: 2,
                    width: 215,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Staff Names',
                    labelAlign: 'right',
                    name: 'SurName',
                    allowBlank: false,
                    emptyText: 'SurName'
                },
                {
                    xtype: 'textfield',
                    x: 330,
                    y: 35,
                    tabIndex: 5,
                    width: 110,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    labelAlign: 'right',
                    name: 'LastName',
                    allowBlank: false,
                    emptyText: 'Last Name'
                },
                {
                    xtype: 'combobox',
                    x: 20,
                    y: 70,
                    tabIndex: 4,
                    width: 185,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Gender',
                    labelAlign: 'right',
                    labelWidth: 70,
                    name: 'Sex',
                    allowBlank: false,
                    emptyText: 'Sex',
                    minChars: 2,
                    queryMode: 'local',
                    store: [
                        'Male',
                        'Female'
                    ]
                },
                {
                    xtype: 'datefield',
                    x: 210,
                    y: 70,
                    tabIndex: 6,
                    width: 230,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Date of Birth',
                    labelAlign: 'right',
                    labelWidth: 90,
                    name: 'DOB',
                    allowBlank: false,
                    blankText: 'The Date of Birth is required',
                    emptyText: 'DOB',
                    selectOnFocus: true,
                    format: 'Y/m/d'
                },
                {
                    xtype: 'combobox',
                    x: -10,
                    y: 105,
                    tabIndex: 7,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Marital Status',
                    labelAlign: 'right',
                    name: 'MaritalStatus',
                    allowBlank: false,
                    emptyText: 'Marital Status',
                    displayField: 'maritals',
                    queryMode: 'local',
                    store: 'MaritalStatusStore',
                    valueField: 'ID'
                },
                {
                    xtype: 'textfield',
                    x: 0,
                    y: 140,
                    tabIndex: 8,
                    width: 265,
                    fieldLabel: 'Nationality',
                    labelAlign: 'right',
                    labelWidth: 90,
                    name: 'Nationality',
                    value: 'Kenyan'
                },
                {
                    xtype: 'textfield',
                    x: 290,
                    y: 135,
                    itemId: 'formStatus',
                    tabIndex: 10,
                    width: 120,
                    name: 'formStatus'
                }
            ]
        },
        {
            xtype: 'fieldset',
            x: 465,
            y: -10,
            height: 230,
            padding: '0 0 0 0',
            width: 390,
            layout: 'absolute',
            title: 'Employee Info',
            items: [
                {
                    xtype: 'combobox',
                    x: 5,
                    y: 145,
                    tabIndex: 13,
                    width: 315,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Employee Status',
                    labelAlign: 'right',
                    labelWidth: 120,
                    name: 'EmpStatus',
                    allowBlank: false,
                    emptyText: 'Employment Status',
                    minChars: 2,
                    queryMode: 'local',
                    store: [
                        'Active',
                        'Inactive',
                        'Retired'
                    ]
                },
                {
                    xtype: 'combobox',
                    x: 45,
                    y: 40,
                    tabIndex: 10,
                    width: 275,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Department',
                    labelAlign: 'right',
                    labelWidth: 80,
                    name: 'Department',
                    allowBlank: false,
                    emptyText: 'Department',
                    displayField: 'deptName',
                    minChars: 3,
                    queryMode: 'local',
                    store: 'PayDeptStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 45,
                    y: 75,
                    tabIndex: 11,
                    width: 275,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Job Title',
                    labelAlign: 'right',
                    labelWidth: 80,
                    name: 'JobTitle',
                    allowBlank: false,
                    emptyText: 'Job Title',
                    displayField: 'JobTitle',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'JobTitlesStore',
                    typeAhead: true,
                    valueField: 'JobTitle'
                },
                {
                    xtype: 'combobox',
                    x: 45,
                    y: 110,
                    tabIndex: 12,
                    width: 220,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Job Group',
                    labelAlign: 'right',
                    labelWidth: 80,
                    name: 'JobGroup',
                    allowBlank: false,
                    emptyText: 'Job Group',
                    displayField: 'groupName',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'JobGroupStore',
                    valueField: 'groupID'
                },
                {
                    xtype: 'combobox',
                    x: 0,
                    y: 5,
                    width: 320,
                    afterLabelTextTpl: [
                        '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                    ],
                    fieldLabel: 'Company Branches',
                    labelAlign: 'right',
                    labelWidth: 125,
                    name: 'EmpBranch',
                    emptyText: 'Comapny Branches',
                    displayField: 'BranchName',
                    minChars: 2,
                    queryMode: 'local',
                    store: [
                        'EMBU',
                        'MERU',
                        'THARAKA NITHI',
                        'NYANDARWA'
                    ],
                    typeAhead: true,
                    valueField: 'BranchName'
                }
            ]
        },
        {
            xtype: 'tabpanel',
            x: 5,
            y: 215,
            height: 270,
            width: 851,
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    height: 236,
                    layout: 'absolute',
                    title: 'Addresses',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 20,
                            tabIndex: 14,
                            width: 405,
                            fieldLabel: 'Addresss',
                            labelAlign: 'right',
                            name: 'Box',
                            emptyText: 'Address'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 160,
                            tabIndex: 18,
                            width: 300,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Phone',
                            labelAlign: 'right',
                            name: 'Phone',
                            allowBlank: false,
                            emptyText: 'Mobile Phone'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 125,
                            tabIndex: 17,
                            width: 300,
                            fieldLabel: 'Email',
                            labelAlign: 'right',
                            name: 'Email',
                            emptyText: 'Email Address'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 90,
                            tabIndex: 16,
                            width: 240,
                            fieldLabel: 'Town',
                            labelAlign: 'right',
                            name: 'Town',
                            emptyText: 'Town'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 55,
                            tabIndex: 15,
                            width: 240,
                            fieldLabel: 'Postal Code',
                            labelAlign: 'right',
                            name: 'PostalCode',
                            emptyText: 'Postal Code'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 276,
                    layout: 'absolute',
                    title: 'Employee Numbers',
                    items: [
                        {
                            xtype: 'textfield',
                            x: -2,
                            y: 10,
                            tabIndex: 19,
                            width: 350,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'ID No ',
                            labelAlign: 'right',
                            name: 'ID_No',
                            allowBlank: false,
                            emptyText: 'ID No'
                        },
                        {
                            xtype: 'textfield',
                            x: 435,
                            y: 90,
                            tabIndex: 27,
                            width: 350,
                            fieldLabel: 'Account No',
                            labelAlign: 'right',
                            name: 'Account_No',
                            emptyText: 'Account No'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 115,
                            tabIndex: 22,
                            width: 350,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'NSSF No',
                            labelAlign: 'right',
                            name: 'NSSF_No',
                            allowBlank: false,
                            emptyText: 'NSSF No'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 185,
                            tabIndex: 24,
                            width: 350,
                            fieldLabel: 'Sacco No',
                            labelAlign: 'right',
                            name: 'SaccoNo',
                            emptyText: 'Sacco No'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 150,
                            tabIndex: 23,
                            width: 350,
                            fieldLabel: 'HELB No',
                            labelAlign: 'right',
                            name: 'HELB_No',
                            emptyText: 'HELB No'
                        },
                        {
                            xtype: 'textfield',
                            x: 0,
                            y: 80,
                            tabIndex: 21,
                            width: 350,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'NHIF No',
                            labelAlign: 'right',
                            name: 'NHIF_No',
                            allowBlank: false,
                            emptyText: 'NHIF No'
                        },
                        {
                            xtype: 'textfield',
                            x: -1,
                            y: 45,
                            tabIndex: 20,
                            width: 350,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'PIN No',
                            labelAlign: 'right',
                            name: 'Pin_No',
                            allowBlank: false,
                            emptyText: 'Pin no'
                        },
                        {
                            xtype: 'combobox',
                            x: 435,
                            y: 20,
                            tabIndex: 25,
                            width: 350,
                            fieldLabel: 'Bank Name',
                            labelAlign: 'right',
                            name: 'BankID',
                            emptyText: 'Bank Name',
                            displayField: 'BankName',
                            minChars: 3,
                            queryMode: 'local',
                            store: 'BankStore',
                            typeAhead: true,
                            valueField: 'BankCode'
                        },
                        {
                            xtype: 'combobox',
                            x: 435,
                            y: 55,
                            tabIndex: 26,
                            width: 350,
                            fieldLabel: 'Branch',
                            labelAlign: 'right',
                            name: 'BranchID',
                            emptyText: 'Bank Branch',
                            displayField: 'BankBranch',
                            minChars: 3,
                            queryMode: 'local',
                            store: 'BankBranchStore',
                            typeAhead: true,
                            valueField: 'Code'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 276,
                    layout: 'absolute',
                    title: 'Employment Details',
                    items: [
                        {
                            xtype: 'combobox',
                            x: 35,
                            y: 10,
                            tabIndex: 28,
                            width: 330,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Employment Type',
                            labelAlign: 'right',
                            labelWidth: 120,
                            name: 'EmpType',
                            allowBlank: false,
                            emptyText: 'Employement Type',
                            displayField: 'EmpType',
                            store: 'EmpTypesStore',
                            valueField: 'EmpType'
                        },
                        {
                            xtype: 'datefield',
                            x: 35,
                            y: 45,
                            tabIndex: 29,
                            width: 280,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Employment Date',
                            labelAlign: 'right',
                            labelWidth: 120,
                            name: 'AppointDate',
                            allowBlank: false,
                            emptyText: 'Employment Date',
                            format: 'Y/m/d'
                        },
                        {
                            xtype: 'datefield',
                            x: 35,
                            y: 80,
                            tabIndex: 30,
                            width: 280,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'End Date',
                            labelAlign: 'right',
                            labelWidth: 120,
                            name: 'AppointEndDate',
                            allowBlank: false,
                            emptyText: 'End Date',
                            format: 'Y/m/d'
                        },
                        {
                            xtype: 'datefield',
                            x: 35,
                            y: 115,
                            tabIndex: 31,
                            width: 280,
                            afterLabelTextTpl: [
                                '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
                            ],
                            fieldLabel: 'Confirmation Date',
                            labelAlign: 'right',
                            labelWidth: 120,
                            name: 'ConfirmDate',
                            allowBlank: false,
                            emptyText: 'Confirmation Date',
                            format: 'Y/m/d'
                        },
                        {
                            xtype: 'checkboxgroup',
                            x: 435,
                            y: 5,
                            frame: true,
                            height: 165,
                            margin: '0 0 0 0',
                            width: 380,
                            layout: 'absolute',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    tabIndex: 29,
                                    name: 'Housed',
                                    boxLabel: 'HOUSED',
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 0,
                                    y: 20,
                                    tabIndex: 29,
                                    name: 'NHIF',
                                    boxLabel: 'NHIF',
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 0,
                                    y: 45,
                                    tabIndex: 30,
                                    name: 'NSSF',
                                    boxLabel: 'NSSF',
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 0,
                                    y: 70,
                                    tabIndex: 31,
                                    name: 'Taxable',
                                    boxLabel: 'TAXABLE',
                                    inputValue: 'yes',
                                    uncheckedValue: 'No'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 0,
                                    y: 95,
                                    tabIndex: 32,
                                    name: 'Pensionable',
                                    boxLabel: 'PENSIONABLE',
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 0,
                                    y: 120,
                                    tabIndex: 33,
                                    name: 'unionisable',
                                    boxLabel: 'UNIONISABLE',
                                    inputValue: 'Yes',
                                    uncheckedValue: 'No'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'button',
            x: 130,
            y: 495,
            height: 35,
            itemId: 'cmdSaveEmployee',
            width: 120,
            iconCls: 'x-fa fa-star',
            text: 'Save'
        },
        {
            xtype: 'button',
            x: 445,
            y: 495,
            height: 40,
            itemId: 'cmdClose',
            width: 120,
            text: 'Close'
        }
    ]

});