/*
 * File: app/view/RegisterWindow.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.RegisterWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.registerwindow',

    requires: [
        'PayrollApp.view.RegisterWindowViewModel'
    ],

    viewModel: {
        type: 'registerwindow'
    },
    resizable: false,
    width: 860,
    title: 'Employee Register',
    maximizable: true,
    minimizable: true

});