/*
 * File: app/view/ReportsMainView.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.ReportsMainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.reportsmainview',

    requires: [
        'PayrollApp.view.ReportsMainViewViewModel',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'reportsmainview'
    },
    height: 720,
    itemId: 'detailPanel',
    padding: ' 10 10 0 20',
    scrollable: true,
    animCollapse: true,
    closable: true,
    collapsible: true,
    title: 'Reports Window',

    tools: [
        {
            xtype: 'tool',
            type: 'minimize'
        },
        {
            xtype: 'tool',
            type: 'maximize'
        }
    ]

});