/*
 * File: app/view/ReturnsReports.js
 * Date: Thu Aug 24 2023 19:15:46 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.ReturnsReports', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.returnsreports',

    requires: [
        'PayrollApp.view.ReturnsReportsViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'returnsreports'
    },
    frame: true,
    height: 211,
    width: 400,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 0,
            y: 5,
            itemId: 'payMonth',
            width: 320,
            fieldLabel: 'Payroll Month',
            labelAlign: 'right',
            displayField: 'month',
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: 0,
            y: 40,
            itemId: 'empBranch',
            width: 320,
            fieldLabel: 'Branch',
            labelAlign: 'right',
            displayField: 'BranchName',
            store: 'PayBranchStore',
            valueField: 'BranchName'
        },
        {
            xtype: 'combobox',
            x: 0,
            y: 75,
            itemId: 'empBranch1',
            width: 320,
            fieldLabel: 'Report Type',
            labelAlign: 'right',
            displayField: 'BranchName',
            store: 'PayBranchStore',
            valueField: 'BranchName'
        },
        {
            xtype: 'button',
            x: 15,
            y: 115,
            height: 40,
            itemId: 'cmdPreviewListing',
            width: 125,
            text: '<b>Preview Report'
        },
        {
            xtype: 'button',
            x: 145,
            y: 115,
            height: 40,
            itemId: 'cmdPrintTrialbalance',
            width: 110,
            text: '<b>Print Report'
        },
        {
            xtype: 'button',
            x: 270,
            y: 115,
            height: 40,
            itemId: 'cmdExportListing',
            width: 110,
            text: '<b>Export Report'
        },
        {
            xtype: 'button',
            x: 230,
            y: 160,
            height: 40,
            itemId: 'cmdClose',
            width: 150,
            text: '<b>Close'
        }
    ]

});