/*
 * File: app/view/SaccoWelfare.js
 * Date: Fri Aug 28 2015 06:32:23 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.SaccoWelfare', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.saccowelfare',

    requires: [
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    frame: true,
    height: 233,
    width: 375,
    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    x: 15,
                    y: 50,
                    itemId: 'payMonth',
                    width: 305,
                    fieldLabel: 'Month From',
                    labelAlign: 'right',
                    displayField: 'month',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 15,
                    y: 80,
                    itemId: 'payMonth1',
                    width: 305,
                    fieldLabel: 'Month To',
                    labelAlign: 'right',
                    displayField: 'month',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayMonthStore',
                    typeAhead: true,
                    valueField: 'ID'
                },
                {
                    xtype: 'combobox',
                    x: 15,
                    y: 20,
                    itemId: 'PaymentType',
                    width: 305,
                    fieldLabel: 'Pay Type',
                    labelAlign: 'right',
                    displayField: 'PayType',
                    minChars: 2,
                    queryMode: 'local',
                    store: 'PayTypeStore',
                    typeAhead: true,
                    valueField: 'PayType'
                },
                {
                    xtype: 'textfield',
                    x: 10,
                    y: 110,
                    itemId: 'pid1',
                    fieldLabel: 'From Pid',
                    labelAlign: 'right',
                    labelWidth: 105
                },
                {
                    xtype: 'button',
                    x: 5,
                    y: 175,
                    height: 25,
                    itemId: 'cmdPreviewPostings',
                    width: 80,
                    text: '<b>Preview</b>'
                },
                {
                    xtype: 'button',
                    x: 90,
                    y: 175,
                    height: 25,
                    itemId: 'cmdPrintPostings',
                    width: 85,
                    text: '<b>Print</b>'
                },
                {
                    xtype: 'button',
                    x: 180,
                    y: 175,
                    height: 25,
                    itemId: 'cmdExportcontributions',
                    width: 85,
                    text: '<b>Export</b>'
                },
                {
                    xtype: 'button',
                    x: 275,
                    y: 175,
                    height: 25,
                    itemId: 'cmdClose',
                    width: 85,
                    text: '<b>Close</b>'
                }
            ]
        });

        me.callParent(arguments);
    }

});