/*
 * File: app/view/SaccoWelfare.js
 * Date: Wed Sep 30 2020 14:12:13 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.view.SaccoWelfare', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.saccowelfare',

    requires: [
        'PayrollApp.view.SaccoWelfareViewModel',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'saccowelfare'
    },
    frame: true,
    height: 233,
    width: 375,
    layout: 'absolute',

    items: [
        {
            xtype: 'combobox',
            x: 10,
            y: 40,
            itemId: 'payMonth',
            width: 305,
            fieldLabel: 'Month From',
            labelAlign: 'right',
            displayField: 'month',
            minChars: 2,
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: 10,
            y: 75,
            itemId: 'payMonth1',
            width: 305,
            fieldLabel: 'Month To',
            labelAlign: 'right',
            displayField: 'month',
            minChars: 2,
            queryMode: 'local',
            store: 'PayMonthStore',
            typeAhead: true,
            valueField: 'ID'
        },
        {
            xtype: 'combobox',
            x: 10,
            y: 5,
            itemId: 'PaymentType',
            width: 305,
            fieldLabel: 'Pay Type',
            labelAlign: 'right',
            displayField: 'PayType',
            minChars: 2,
            queryMode: 'local',
            store: 'PayTypeStore',
            typeAhead: true,
            valueField: 'PayType'
        },
        {
            xtype: 'textfield',
            x: 5,
            y: 110,
            itemId: 'pid1',
            fieldLabel: 'From Pid',
            labelAlign: 'right',
            labelWidth: 105
        },
        {
            xtype: 'button',
            x: 5,
            y: 175,
            height: 25,
            itemId: 'cmdPreviewPostings',
            width: 80,
            text: '<b>Preview</b>'
        },
        {
            xtype: 'button',
            x: 90,
            y: 175,
            height: 25,
            itemId: 'cmdPrintPostings',
            width: 85,
            text: '<b>Print</b>'
        },
        {
            xtype: 'button',
            x: 180,
            y: 175,
            height: 25,
            itemId: 'cmdExportcontributions',
            width: 85,
            text: '<b>Export</b>'
        },
        {
            xtype: 'button',
            x: 275,
            y: 175,
            height: 25,
            itemId: 'cmdClose',
            width: 85,
            text: '<b>Close</b>'
        }
    ]

});