/*
 * File: app/model/Earnings.js
 * Date: Thu Aug 24 2023 19:15:50 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.model.Earnings', {
    extend: 'Ext.data.Model',
    alias: 'model.earnings',

    requires: [
        'Ext.data.field.Field'
    ],
    uses: [
        'PayrollApp.model.SlipEmpInfo'
    ],

    fields: [
        {
            name: 'PID',
            sortType: 'asInt'
        },
        {
            name: 'EmpNames'
        },
        {
            name: 'Category'
        },
        {
            name: 'PayType'
        },
        {
            name: 'Amount'
        },
        {
            name: 'Balance'
        }
    ],

    belongsTo: {
        model: 'PayrollApp.model.SlipEmpInfo'
    }
});