/*
 * File: app/model/EmployeesRegister.js
 * Date: Sun Mar 08 2015 18:18:19 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.model.EmployeesRegister', {
    extend: 'Ext.data.Model',
    alias: 'model.employeesregister',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            mapping: 'PID',
            name: 'PID',
            sortType: 'asInt'
        },
        {
            mapping: 'FirstName',
            name: 'FirstName'
        },
        {
            mapping: 'LastName',
            name: 'LastName'
        },
        {
            mapping: 'SurName',
            name: 'SurName'
        },
        {
            mapping: 'Department',
            name: 'Department'
        },
        {
            mapping: 'JobTitle',
            name: 'JobTitle'
        },
        {
            mapping: 'Box',
            name: 'Box'
        },
        {
            mapping: 'PostalCode',
            name: 'PostalCode'
        },
        {
            mapping: 'Phone',
            name: 'Phone'
        },
        {
            mapping: 'Town',
            name: 'Town'
        },
        {
            mapping: 'Email',
            name: 'Email'
        },
        {
            mapping: 'ID_No',
            name: 'ID_No'
        },
        {
            mapping: 'Pin_No',
            name: 'Pin_No'
        },
        {
            mapping: 'NSSF_No',
            name: 'NSSF_No'
        },
        {
            mapping: 'NHIF_No',
            name: 'NHIF_No'
        },
        {
            mapping: 'Account_No',
            name: 'Account_No'
        },
        {
            mapping: 'EmpType',
            name: 'EmpType'
        },
        {
            mapping: 'AppointDate',
            name: 'AppointDate'
        },
        {
            mapping: 'AppointEndDate',
            name: 'AppointEndDate'
        },
        {
            mapping: 'ConfirmDate',
            name: 'ConfirmDate'
        },
        {
            mapping: 'Nationality',
            name: 'Nationality'
        },
        {
            mapping: 'MaritalStatus',
            name: 'MaritalStatus'
        },
        {
            mapping: 'DOB',
            name: 'DOB'
        },
        {
            mapping: 'Sex',
            name: 'Sex'
        },
        {
            mapping: 'BankID',
            name: 'BankID'
        },
        {
            mapping: 'BranchID',
            name: 'BranchID'
        },
        {
            mapping: 'EmpBranch',
            name: 'EmpBranch'
        },
        {
            mapping: 'JobGroup',
            name: 'JobGroup'
        },
        {
            mapping: 'Taxable',
            name: 'Taxable'
        },
        {
            mapping: 'Pensionable',
            name: 'Pensionable'
        },
        {
            mapping: 'Unionisable',
            name: 'Unionisable'
        },
        {
            mapping: 'Housed',
            name: 'Housed'
        },
        {
            mapping: 'NSSF',
            name: 'NSSF'
        },
        {
            mapping: 'NHIF',
            name: 'NHIF'
        },
        {
            mapping: 'EmpStatus',
            name: 'EmpStatus'
        },
        {
            name: 'GratuityRates'
        },
        {
            name: 'HELB_No'
        },
        {
            name: 'SaccoNo'
        }
    ]
});