/*
 * File: app/model/PayrollListingsMainModel.js
 * Date: Thu Aug 24 2023 19:15:50 GMT+0300 (East Africa Time)
 *
 * This file was generated by Sencha Architect version 4.3.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.model.PayrollListingsMainModel', {
    extend: 'Ext.data.Model',
    alias: 'model.payrolllistingsmainmodel',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],
    uses: [
        'PayrollApp.model.PayrollStatus'
    ],

    fields: [
        {
            name: 'Pid'
        },
        {
            name: 'EmpNames'
        },
        {
            name: 'JobTitle'
        },
        {
            type: 'int',
            name: 'BasicPay'
        },
        {
            type: 'int',
            mapping: 'HouseAllowance',
            name: 'HouseAllowance'
        },
        {
            mapping: 'Transport',
            name: 'Transport'
        },
        {
            type: 'int',
            mapping: 'CallAllowance',
            name: 'CallAllowance'
        },
        {
            type: 'int',
            mapping: 'Locum',
            name: 'Locum'
        },
        {
            type: 'int',
            mapping: 'RiskAllowance',
            name: 'RiskAllowance'
        },
        {
            type: 'int',
            mapping: 'NonPractice',
            name: 'NonPractice'
        },
        {
            type: 'int',
            mapping: 'LeaveAllowance',
            name: 'LeaveAllowance'
        },
        {
            name: 'Gratuity'
        },
        {
            type: 'int',
            mapping: 'GrossPay',
            name: 'GrossPay'
        },
        {
            mapping: 'NHIF',
            name: 'NHIF'
        },
        {
            type: 'string',
            mapping: 'NSSF',
            name: 'NSSF'
        },
        {
            type: 'string',
            mapping: 'PAYE',
            name: 'PAYE'
        },
        {
            mapping: 'Welfare',
            name: 'Welfare'
        },
        {
            name: 'BarclaysLoan'
        },
        {
            mapping: 'Food',
            name: 'Food'
        },
        {
            name: 'Condolence'
        },
        {
            mapping: 'Advance',
            name: 'Advance'
        },
        {
            mapping: 'TotalDeductions',
            name: 'TotalDeductions'
        },
        {
            mapping: 'TotalPay',
            name: 'TotalPay'
        },
        {
            mapping: 'NetPay',
            name: 'NetPay'
        },
        {
            name: 'OtherDeductions'
        }
    ],

    belongsTo: {
        model: 'PayrollApp.model.PayrollStatus'
    }
});