/*
 * File: app/model/PayrollListingsMainModel.js
 * Date: Thu Aug 27 2015 16:57:36 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.model.PayrollListingsMainModel', {
    extend: 'Ext.data.Model',
    alias: 'model.payrolllistingsmainmodel',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.BelongsTo'
    ],
    uses: [
        'PayrollApp.model.PayrollStatus'
    ],

    fields: [
        {
            name: 'Pid'
        },
        {
            name: 'EmpNames'
        },
        {
            name: 'JobTitle'
        },
        {
            name: 'BasicPay',
            type: 'int'
        },
        {
            mapping: 'HouseAllowance',
            name: 'HouseAllowance',
            type: 'int'
        },
        {
            mapping: 'Medical',
            name: 'Medical',
            type: 'int'
        },
        {
            mapping: 'Transport',
            name: 'Transport',
            type: 'int'
        },
        {
            mapping: 'RiskAllowance',
            name: 'RiskAllowance',
            type: 'int'
        },
        {
            mapping: 'NonPractice',
            name: 'NonPractice',
            type: 'int'
        },
        {
            mapping: 'LeaveAllowance',
            name: 'LeaveAllowance',
            type: 'int'
        },
        {
            name: 'CaritasAllowance'
        },
        {
            name: 'MaryKnollAllowance'
        },
        {
            name: 'CHAKAllowance'
        },
        {
            name: 'SisterAllowance'
        },
        {
            mapping: 'GrossPay',
            name: 'GrossPay',
            type: 'int'
        },
        {
            mapping: 'NHIF',
            name: 'NHIF'
        },
        {
            mapping: 'NSSF',
            name: 'NSSF',
            type: 'string'
        },
        {
            mapping: 'PAYE',
            name: 'PAYE',
            type: 'string'
        },
        {
            mapping: 'Waumini',
            name: 'Waumini'
        },
        {
            name: 'WauminiRepayment'
        },
        {
            name: 'WauminiInsurance'
        },
        {
            mapping: 'Advance',
            name: 'Advance'
        },
        {
            mapping: 'Loan',
            name: 'Loan'
        },
        {
            mapping: 'Welfare',
            name: 'Welfare'
        },
        {
            name: 'WelfareRepayment'
        },
        {
            mapping: 'TotalDeductions',
            name: 'TotalDeductions'
        },
        {
            mapping: 'TotalPay',
            name: 'TotalPay'
        },
        {
            mapping: 'Netpay',
            name: 'NetPay'
        }
    ],

    belongsTo: {
        model: 'PayrollApp.model.PayrollStatus'
    }
});