/*
 * File: app/model/SlipEmpInfo.js
 * Date: Sun Mar 08 2015 15:46:56 GMT+0300 (E. Africa Standard Time)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PayrollApp.model.SlipEmpInfo', {
    extend: 'Ext.data.Model',
    alias: 'model.slipempinfo',

    requires: [
        'Ext.data.Field',
        'Ext.data.association.HasMany'
    ],
    uses: [
        'PayrollApp.model.Earnings'
    ],

    fields: [
        {
            name: 'pid'
        },
        {
            name: 'ColNumber'
        },
        {
            name: 'companyname'
        },
        {
            name: 'empNames'
        },
        {
            name: 'period'
        },
        {
            name: 'empBranch'
        },
        {
            name: 'department'
        },
        {
            name: 'pin_No'
        },
        {
            name: 'GrossPay'
        },
        {
            name: 'TaxDeducted'
        },
        {
            name: 'TotalDeduction'
        },
        {
            name: 'NetPay'
        }
    ],

    hasMany: {
        model: 'PayrollApp.model.Earnings',
        primaryKey: 'pid',
        autoLoad: true,
        foreignKey: 'pid',
        name: 'Earnings'
    }
});