/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'LoginSession',
        'PayrollMonths'
    ],
    stores: [
        'PayMonthsStore',
        'LoginSessions'
    ],
    views: [
        'ImportPayments'
    ],
    controllers: [
        'MainApp',
        'deleteActions',
        'UserManagement',
        'UpdateActions',
        'ReportsActions'
    ],
    name: 'PayrollApp',

    launch: function() {
        var loginSess=Ext.data.StoreManager.lookup('LoginSessions');

        loginSess.load({
            callback:function(records, operation, success){
               // Ext.Msg.alert('Count',loginSess.getCount());
                if(loginSess.getCount()==='' || loginSess.getCount()===0){
                     Ext.create('PayrollApp.view.LoginMain' , {renderTo: Ext.getBody()});
                }else{
                    Ext.create('PayrollApp.view.PayrollMain' , {renderTo: Ext.getBody()});
                }
            },
            scope:this
        });


    }

});
