/*
 * File: app/view/loginform.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.loginform', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    minHeight: 700,
    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    manageHeight: false,
    title: 'Login Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    x: 590,
                    y: 180,
                    height: 150,
                    width: 435,
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'image',
                            x: -3,
                            y: 5,
                            height: 45,
                            width: 175,
                            src: '../images/care_logo_mysql.gif'
                        },
                        {
                            xtype: 'label',
                            x: 175,
                            y: 35,
                            height: 25,
                            html: '<b>Payroll Login</b>',
                            width: 110,
                            text: ''
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 75,
                            width: 310,
                            fieldLabel: 'Username',
                            name: 'txtUserName'
                        },
                        {
                            xtype: 'textfield',
                            x: 30,
                            y: 110,
                            width: 310,
                            fieldLabel: 'Password',
                            name: 'txtPassword'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 800,
                    y: 335,
                    height: 25,
                    itemId: 'cmdLogin',
                    width: 105,
                    text: 'Login'
                },
                {
                    xtype: 'button',
                    x: 920,
                    y: 335,
                    height: 25,
                    itemId: 'cmdClose',
                    width: 105,
                    text: 'Cancel'
                }
            ]
        });

        me.callParent(arguments);
    }

});